class CompletaPaises2022 < ActiveRecord::Migration[7.0]
  def up
    rename_column :sip_pais, :nombreiso, :nombreosm
    add_column :sip_pais, :nombreiso_ingles, :string, limit: 512
    add_column :sip_pais, :nombreiso_frances, :string, limit: 512
    execute <<-SQL
      INSERT INTO sip_pais (id, nombre, nombreosm, nombreiso_ingles, nombreiso_frances, latitud, longitud, alfa2, alfa3, codiso, fechacreacion, created_at, updated_at, observaciones)
        VALUES (876, 'Wallis y Futuna', 'Wallis y Futuna', 'Wallis and Futuna', 'Wallis et Futuna', '-13.283333', '-176.183333', 'WF', 'WLF', '876', '2022-04-13', '2022-04-13', '2022-04-13', 'De https://www.iso.org/obp/ui/#search/code/ copiado en https://gitlab.com/pasosdeJesus/division-politica/-/blob/main/PAISES_ISO_2022.csv. Coordenadas de Wikipedia.');
      UPDATE sip_pais SET nombreiso_ingles='Antarctica', nombreiso_frances='Antarctique (l'')', codiso=10 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=10;
      UPDATE sip_pais SET nombreiso_ingles='Bulgaria', nombreiso_frances='Bulgarie (la)', codiso=100 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=100;
      UPDATE sip_pais SET nombreiso_ingles='Myanmar', nombreiso_frances='Myanmar (le)', codiso=104 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=104;
      UPDATE sip_pais SET nombreiso_ingles='Burundi', nombreiso_frances='Burundi (le)', codiso=108 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=108;
      UPDATE sip_pais SET nombreiso_ingles='Belarus', nombreiso_frances='Bélarus (le)', codiso=112 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=112;
      UPDATE sip_pais SET nombreiso_ingles='Cambodia', nombreiso_frances='Cambodge (le)', codiso=116 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=116;
      UPDATE sip_pais SET nombreiso_ingles='Algeria', nombreiso_frances='Algérie (l'')', codiso=12 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=12;
      UPDATE sip_pais SET nombreiso_ingles='Cameroon', nombreiso_frances='Cameroun (le)', codiso=120 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=120;
      UPDATE sip_pais SET nombreiso_ingles='Canada', nombreiso_frances='Canada (le)', codiso=124 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=124;
      UPDATE sip_pais SET nombreiso_ingles='Cabo Verde', nombreiso_frances='Cabo Verde', codiso=132 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=132;
      UPDATE sip_pais SET nombreiso_ingles='Cayman Islands (the)', nombreiso_frances='Caïmans (les Îles)', codiso=136 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=136;
      UPDATE sip_pais SET nombreiso_ingles='Central African Republic (the)', nombreiso_frances='République centrafricaine (la)', codiso=140 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=140;
      UPDATE sip_pais SET nombreiso_ingles='Sri Lanka', nombreiso_frances='Sri Lanka', codiso=144 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=144;
      UPDATE sip_pais SET nombreiso_ingles='Chad', nombreiso_frances='Tchad (le)', codiso=148 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=148;
      UPDATE sip_pais SET nombreiso_ingles='Chile', nombreiso_frances='Chili (le)', codiso=152 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=152;
      UPDATE sip_pais SET nombreiso_ingles='China', nombreiso_frances='Chine (la)', codiso=156 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=156;
      UPDATE sip_pais SET nombreiso_ingles='Taiwan (Province of China)', nombreiso_frances='Taïwan (Province de Chine)', codiso=158 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=158;
      UPDATE sip_pais SET nombreiso_ingles='American Samoa', nombreiso_frances='Samoa américaines (les)', codiso=16 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=16;
      UPDATE sip_pais SET nombreiso_ingles='Christmas Island', nombreiso_frances='Christmas (l''Île)', codiso=162 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=162;
      UPDATE sip_pais SET nombreiso_ingles='Cocos (Keeling) Islands (the)', nombreiso_frances='Cocos (les Îles)/ Keeling (les Îles)', codiso=166 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=166;
      UPDATE sip_pais SET nombreiso_ingles='Colombia', nombreiso_frances='Colombie (la)', codiso=170 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=170;
      UPDATE sip_pais SET nombreiso_ingles='Comoros (the)', nombreiso_frances='Comores (les)', codiso=174 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=174;
      UPDATE sip_pais SET nombreiso_ingles='Mayotte', nombreiso_frances='Mayotte', codiso=175 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=175;
      UPDATE sip_pais SET nombreiso_ingles='Congo (the)', nombreiso_frances='Congo (le)', codiso=178 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=178;
      UPDATE sip_pais SET nombreiso_ingles='Congo (the Democratic Republic of the)', nombreiso_frances='Congo (la République démocratique du)', codiso=180 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=180;
      UPDATE sip_pais SET nombreiso_ingles='Cook Islands (the)', nombreiso_frances='Cook (les Îles)', codiso=184 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=184;
      UPDATE sip_pais SET nombreiso_ingles='Costa Rica', nombreiso_frances='Costa Rica (le)', codiso=188 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=188;
      UPDATE sip_pais SET nombreiso_ingles='Croatia', nombreiso_frances='Croatie (la)', codiso=191 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=191;
      UPDATE sip_pais SET nombreiso_ingles='Cuba', nombreiso_frances='Cuba', codiso=192 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=192;
      UPDATE sip_pais SET nombreiso_ingles='Cyprus', nombreiso_frances='Chypre', codiso=196 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=196;
      UPDATE sip_pais SET nombreiso_ingles='Andorra', nombreiso_frances='Andorre (l'')', codiso=20 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=20;
      UPDATE sip_pais SET nombreiso_ingles='Czechia', nombreiso_frances='Tchéquie (la)', codiso=203 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=203;
      UPDATE sip_pais SET nombreiso_ingles='Benin', nombreiso_frances='Bénin (le)', codiso=204 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=204;
      UPDATE sip_pais SET nombreiso_ingles='Denmark', nombreiso_frances='Danemark (le)', codiso=208 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=208;
      UPDATE sip_pais SET nombreiso_ingles='Dominica', nombreiso_frances='Dominique (la)', codiso=212 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=212;
      UPDATE sip_pais SET nombreiso_ingles='Dominican Republic (the)', nombreiso_frances='dominicaine (la République)', codiso=214 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=214;
      UPDATE sip_pais SET nombreiso_ingles='Ecuador', nombreiso_frances='Équateur (l'')', codiso=218 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=218;
      UPDATE sip_pais SET nombreiso_ingles='El Salvador', nombreiso_frances='El Salvador', codiso=222 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=222;
      UPDATE sip_pais SET nombreiso_ingles='Equatorial Guinea', nombreiso_frances='Guinée équatoriale (la)', codiso=226 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=226;
      UPDATE sip_pais SET nombreiso_ingles='Ethiopia', nombreiso_frances='Éthiopie (l'')', codiso=231 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=231;
      UPDATE sip_pais SET nombreiso_ingles='Eritrea', nombreiso_frances='Érythrée (l'')', codiso=232 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=232;
      UPDATE sip_pais SET nombreiso_ingles='Estonia', nombreiso_frances='Estonie (l'')', codiso=233 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=233;
      UPDATE sip_pais SET nombreiso_ingles='Faroe Islands (the)', nombreiso_frances='Féroé (les Îles)', codiso=234 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=234;
      UPDATE sip_pais SET nombreiso_ingles='Falkland Islands (the) [Malvinas]', nombreiso_frances='Falkland (les Îles)/Malouines (les Îles)', codiso=238 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=238;
      UPDATE sip_pais SET nombreiso_ingles='South Georgia and the South Sandwich Islands', nombreiso_frances='Géorgie du Sud-et-les Îles Sandwich du Sud (la)', codiso=239 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=239;
      UPDATE sip_pais SET nombreiso_ingles='Angola', nombreiso_frances='Angola (l'')', codiso=24 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=24;
      UPDATE sip_pais SET nombreiso_ingles='Fiji', nombreiso_frances='Fidji (les)', codiso=242 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=242;
      UPDATE sip_pais SET nombreiso_ingles='Finland', nombreiso_frances='Finlande (la)', codiso=246 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=246;
      UPDATE sip_pais SET nombreiso_ingles='Åland Islands', nombreiso_frances='Åland(les Îles)', codiso=248 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=248;
      UPDATE sip_pais SET nombreiso_ingles='France', nombreiso_frances='France (la)', codiso=250 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=250;
      UPDATE sip_pais SET nombreiso_ingles='French Guiana', nombreiso_frances='Guyane française (la )', codiso=254 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=254;
      UPDATE sip_pais SET nombreiso_ingles='French Polynesia', nombreiso_frances='Polynésie française (la)', codiso=258 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=258;
      UPDATE sip_pais SET nombreiso_ingles='French Southern Territories (the)', nombreiso_frances='Terres australes françaises (les)', codiso=260 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=260;
      UPDATE sip_pais SET nombreiso_ingles='Djibouti', nombreiso_frances='Djibouti', codiso=262 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=262;
      UPDATE sip_pais SET nombreiso_ingles='Gabon', nombreiso_frances='Gabon (le)', codiso=266 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=266;
      UPDATE sip_pais SET nombreiso_ingles='Georgia', nombreiso_frances='Géorgie (la)', codiso=268 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=268;
      UPDATE sip_pais SET nombreiso_ingles='Gambia (the)', nombreiso_frances='Gambie (la)', codiso=270 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=270;
      UPDATE sip_pais SET nombreiso_ingles='Palestine, State of', nombreiso_frances='Palestine, État de', codiso=275 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=275;
      UPDATE sip_pais SET nombreiso_ingles='Germany', nombreiso_frances='Allemagne (l'')', codiso=276 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=276;
      UPDATE sip_pais SET nombreiso_ingles='Antigua and Barbuda', nombreiso_frances='Antigua-et-Barbuda', codiso=28 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=28;
      UPDATE sip_pais SET nombreiso_ingles='Ghana', nombreiso_frances='Ghana (le)', codiso=288 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=288;
      UPDATE sip_pais SET nombreiso_ingles='Gibraltar', nombreiso_frances='Gibraltar', codiso=292 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=292;
      UPDATE sip_pais SET nombreiso_ingles='Kiribati', nombreiso_frances='Kiribati', codiso=296 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=296;
      UPDATE sip_pais SET nombreiso_ingles='Greece', nombreiso_frances='Grèce (la)', codiso=300 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=300;
      UPDATE sip_pais SET nombreiso_ingles='Greenland', nombreiso_frances='Groenland (le)', codiso=304 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=304;
      UPDATE sip_pais SET nombreiso_ingles='Grenada', nombreiso_frances='Grenade (la)', codiso=308 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=308;
      UPDATE sip_pais SET nombreiso_ingles='Azerbaijan', nombreiso_frances='Azerbaïdjan (l'')', codiso=31 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=31;
      UPDATE sip_pais SET nombreiso_ingles='Guadeloupe', nombreiso_frances='Guadeloupe (la)', codiso=312 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=312;
      UPDATE sip_pais SET nombreiso_ingles='Guam', nombreiso_frances='Guam', codiso=316 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=316;
      UPDATE sip_pais SET nombreiso_ingles='Argentina', nombreiso_frances='Argentine (l'')', codiso=32 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=32;
      UPDATE sip_pais SET nombreiso_ingles='Guatemala', nombreiso_frances='Guatemala (le)', codiso=320 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=320;
      UPDATE sip_pais SET nombreiso_ingles='Guinea', nombreiso_frances='Guinée (la)', codiso=324 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=324;
      UPDATE sip_pais SET nombreiso_ingles='Guyana', nombreiso_frances='Guyana (le)', codiso=328 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=328;
      UPDATE sip_pais SET nombreiso_ingles='Haiti', nombreiso_frances='Haïti', codiso=332 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=332;
      UPDATE sip_pais SET nombreiso_ingles='Heard Island and McDonald Islands', nombreiso_frances='Heard-et-Îles MacDonald (l''Île)', codiso=334 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=334;
      UPDATE sip_pais SET nombreiso_ingles='Holy See (the)', nombreiso_frances='Saint-Siège (le)', codiso=336 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=336;
      UPDATE sip_pais SET nombreiso_ingles='Honduras', nombreiso_frances='Honduras (le)', codiso=340 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=340;
      UPDATE sip_pais SET nombreiso_ingles='Hong Kong', nombreiso_frances='Hong Kong', codiso=344 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=344;
      UPDATE sip_pais SET nombreiso_ingles='Hungary', nombreiso_frances='Hongrie (la)', codiso=348 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=348;
      UPDATE sip_pais SET nombreiso_ingles='Iceland', nombreiso_frances='Islande (l'')', codiso=352 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=352;
      UPDATE sip_pais SET nombreiso_ingles='India', nombreiso_frances='Inde (l'')', codiso=356 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=356;
      UPDATE sip_pais SET nombreiso_ingles='Australia', nombreiso_frances='Australie (l'')', codiso=36 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=36;
      UPDATE sip_pais SET nombreiso_ingles='Indonesia', nombreiso_frances='Indonésie (l'')', codiso=360 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=360;
      UPDATE sip_pais SET nombreiso_ingles='Iran (Islamic Republic of)', nombreiso_frances='Iran (République Islamique d'')', codiso=364 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=364;
      UPDATE sip_pais SET nombreiso_ingles='Iraq', nombreiso_frances='Iraq (l'')', codiso=368 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=368;
      UPDATE sip_pais SET nombreiso_ingles='Ireland', nombreiso_frances='Irlande (l'')', codiso=372 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=372;
      UPDATE sip_pais SET nombreiso_ingles='Israel', nombreiso_frances='Israël', codiso=376 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=376;
      UPDATE sip_pais SET nombreiso_ingles='Italy', nombreiso_frances='Italie (l'')', codiso=380 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=380;
      UPDATE sip_pais SET nombreiso_ingles='Côte d''Ivoire', nombreiso_frances='Côte d''Ivoire (la)', codiso=384 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=384;
      UPDATE sip_pais SET nombreiso_ingles='Jamaica', nombreiso_frances='Jamaïque (la)', codiso=388 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=388;
      UPDATE sip_pais SET nombreiso_ingles='Japan', nombreiso_frances='Japon (le)', codiso=392 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=392;
      UPDATE sip_pais SET nombreiso_ingles='Kazakhstan', nombreiso_frances='Kazakhstan (le)', codiso=398 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=398;
      UPDATE sip_pais SET nombreiso_ingles='Afghanistan', nombreiso_frances='Afghanistan (l'')', codiso=4 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=4;
      UPDATE sip_pais SET nombreiso_ingles='Austria', nombreiso_frances='Autriche (l'')', codiso=40 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=40;
      UPDATE sip_pais SET nombreiso_ingles='Jordan', nombreiso_frances='Jordanie (la)', codiso=400 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=400;
      UPDATE sip_pais SET nombreiso_ingles='Kenya', nombreiso_frances='Kenya (le)', codiso=404 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=404;
      UPDATE sip_pais SET nombreiso_ingles='Korea (the Democratic People''s Republic of)', nombreiso_frances='Corée (la République populaire démocratique de)', codiso=408 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=408;
      UPDATE sip_pais SET nombreiso_ingles='Korea (the Republic of)', nombreiso_frances='Corée (la République de)', codiso=410 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=410;
      UPDATE sip_pais SET nombreiso_ingles='Kuwait', nombreiso_frances='Koweït (le)', codiso=414 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=414;
      UPDATE sip_pais SET nombreiso_ingles='Kyrgyzstan', nombreiso_frances='Kirghizistan (le)', codiso=417 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=417;
      UPDATE sip_pais SET nombreiso_ingles='Lao People''s Democratic Republic (the)', nombreiso_frances='Lao (la République démocratique populaire)', codiso=418 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=418;
      UPDATE sip_pais SET nombreiso_ingles='Lebanon', nombreiso_frances='Liban (le)', codiso=422 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=422;
      UPDATE sip_pais SET nombreiso_ingles='Lesotho', nombreiso_frances='Lesotho (le)', codiso=426 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=426;
      UPDATE sip_pais SET nombreiso_ingles='Latvia', nombreiso_frances='Lettonie (la)', codiso=428 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=428;
      UPDATE sip_pais SET nombreiso_ingles='Liberia', nombreiso_frances='Libéria (le)', codiso=430 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=430;
      UPDATE sip_pais SET nombreiso_ingles='Libya', nombreiso_frances='Libye (la)', codiso=434 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=434;
      UPDATE sip_pais SET nombreiso_ingles='Liechtenstein', nombreiso_frances='Liechtenstein (le)', codiso=438 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=438;
      UPDATE sip_pais SET nombreiso_ingles='Bahamas (the)', nombreiso_frances='Bahamas (les)', codiso=44 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=44;
      UPDATE sip_pais SET nombreiso_ingles='Lithuania', nombreiso_frances='Lituanie (la)', codiso=440 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=440;
      UPDATE sip_pais SET nombreiso_ingles='Luxembourg', nombreiso_frances='Luxembourg (le)', codiso=442 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=442;
      UPDATE sip_pais SET nombreiso_ingles='Macao', nombreiso_frances='Macao', codiso=446 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=446;
      UPDATE sip_pais SET nombreiso_ingles='Madagascar', nombreiso_frances='Madagascar', codiso=450 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=450;
      UPDATE sip_pais SET nombreiso_ingles='Malawi', nombreiso_frances='Malawi (le)', codiso=454 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=454;
      UPDATE sip_pais SET nombreiso_ingles='Malaysia', nombreiso_frances='Malaisie (la)', codiso=458 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=458;
      UPDATE sip_pais SET nombreiso_ingles='Maldives', nombreiso_frances='Maldives (les)', codiso=462 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=462;
      UPDATE sip_pais SET nombreiso_ingles='Mali', nombreiso_frances='Mali (le)', codiso=466 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=466;
      UPDATE sip_pais SET nombreiso_ingles='Malta', nombreiso_frances='Malte', codiso=470 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=470;
      UPDATE sip_pais SET nombreiso_ingles='Martinique', nombreiso_frances='Martinique (la)', codiso=474 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=474;
      UPDATE sip_pais SET nombreiso_ingles='Mauritania', nombreiso_frances='Mauritanie (la)', codiso=478 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=478;
      UPDATE sip_pais SET nombreiso_ingles='Bahrain', nombreiso_frances='Bahreïn', codiso=48 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=48;
      UPDATE sip_pais SET nombreiso_ingles='Mauritius', nombreiso_frances='Maurice', codiso=480 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=480;
      UPDATE sip_pais SET nombreiso_ingles='Mexico', nombreiso_frances='Mexique (le)', codiso=484 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=484;
      UPDATE sip_pais SET nombreiso_ingles='Monaco', nombreiso_frances='Monaco', codiso=492 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=492;
      UPDATE sip_pais SET nombreiso_ingles='Mongolia', nombreiso_frances='Mongolie (la)', codiso=496 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=496;
      UPDATE sip_pais SET nombreiso_ingles='Moldova (the Republic of)', nombreiso_frances='Moldova (la République de)', codiso=498 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=498;
      UPDATE sip_pais SET nombreiso_ingles='Montenegro', nombreiso_frances='Monténégro (le)', codiso=499 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=499;
      UPDATE sip_pais SET nombreiso_ingles='Bangladesh', nombreiso_frances='Bangladesh (le)', codiso=50 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=50;
      UPDATE sip_pais SET nombreiso_ingles='Montserrat', nombreiso_frances='Montserrat', codiso=500 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=500;
      UPDATE sip_pais SET nombreiso_ingles='Morocco', nombreiso_frances='Maroc (le)', codiso=504 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=504;
      UPDATE sip_pais SET nombreiso_ingles='Mozambique', nombreiso_frances='Mozambique (le)', codiso=508 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=508;
      UPDATE sip_pais SET nombreiso_ingles='Armenia', nombreiso_frances='Arménie (l'')', codiso=51 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=51;
      UPDATE sip_pais SET nombreiso_ingles='Oman', nombreiso_frances='Oman', codiso=512 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=512;
      UPDATE sip_pais SET nombreiso_ingles='Namibia', nombreiso_frances='Namibie (la)', codiso=516 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=516;
      UPDATE sip_pais SET nombreiso_ingles='Barbados', nombreiso_frances='Barbade (la)', codiso=52 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=52;
      UPDATE sip_pais SET nombreiso_ingles='Nauru', nombreiso_frances='Nauru', codiso=520 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=520;
      UPDATE sip_pais SET nombreiso_ingles='Nepal', nombreiso_frances='Népal (le)', codiso=524 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=524;
      UPDATE sip_pais SET nombreiso_ingles='Netherlands (the)', nombreiso_frances='Pays-Bas (les)', codiso=528 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=528;
      UPDATE sip_pais SET nombreiso_ingles='Curaçao', nombreiso_frances='Curaçao', codiso=531 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=531;
      UPDATE sip_pais SET nombreiso_ingles='Aruba', nombreiso_frances='Aruba', codiso=533 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=533;
      UPDATE sip_pais SET nombreiso_ingles='Sint Maarten (Dutch part)', nombreiso_frances='Saint-Martin (partie néerlandaise)', codiso=534 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=534;
      UPDATE sip_pais SET nombreiso_ingles='Bonaire, Sint Eustatius and Saba', nombreiso_frances='Bonaire, Saint-Eustache et Saba', codiso=535 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=535;
      UPDATE sip_pais SET nombreiso_ingles='New Caledonia', nombreiso_frances='Nouvelle-Calédonie (la)', codiso=540 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=540;
      UPDATE sip_pais SET nombreiso_ingles='Vanuatu', nombreiso_frances='Vanuatu (le)', codiso=548 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=548;
      UPDATE sip_pais SET nombreiso_ingles='New Zealand', nombreiso_frances='Nouvelle-Zélande (la)', codiso=554 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=554;
      UPDATE sip_pais SET nombreiso_ingles='Nicaragua', nombreiso_frances='Nicaragua (le)', codiso=558 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=558;
      UPDATE sip_pais SET nombreiso_ingles='Belgium', nombreiso_frances='Belgique (la)', codiso=56 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=56;
      UPDATE sip_pais SET nombreiso_ingles='Niger (the)', nombreiso_frances='Niger (le)', codiso=562 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=562;
      UPDATE sip_pais SET nombreiso_ingles='Nigeria', nombreiso_frances='Nigéria (le)', codiso=566 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=566;
      UPDATE sip_pais SET nombreiso_ingles='Niue', nombreiso_frances='Niue', codiso=570 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=570;
      UPDATE sip_pais SET nombreiso_ingles='Norfolk Island', nombreiso_frances='Norfolk (l''Île)', codiso=574 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=574;
      UPDATE sip_pais SET nombreiso_ingles='Norway', nombreiso_frances='Norvège (la)', codiso=578 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=578;
      UPDATE sip_pais SET nombreiso_ingles='Northern Mariana Islands (the)', nombreiso_frances='Mariannes du Nord (les Îles)', codiso=580 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=580;
      UPDATE sip_pais SET nombreiso_ingles='United States Minor Outlying Islands (the)', nombreiso_frances='Îles mineures éloignées des États-Unis (les)', codiso=581 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=581;
      UPDATE sip_pais SET nombreiso_ingles='Micronesia (Federated States of)', nombreiso_frances='Micronésie (États fédérés de)', codiso=583 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=583;
      UPDATE sip_pais SET nombreiso_ingles='Marshall Islands (the)', nombreiso_frances='Marshall (les Îles)', codiso=584 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=584;
      UPDATE sip_pais SET nombreiso_ingles='Palau', nombreiso_frances='Palaos (les)', codiso=585 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=585;
      UPDATE sip_pais SET nombreiso_ingles='Pakistan', nombreiso_frances='Pakistan (le)', codiso=586 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=586;
      UPDATE sip_pais SET nombreiso_ingles='Panama', nombreiso_frances='Panama (le)', codiso=591 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=591;
      UPDATE sip_pais SET nombreiso_ingles='Papua New Guinea', nombreiso_frances='Papouasie-Nouvelle-Guinée (la)', codiso=598 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=598;
      UPDATE sip_pais SET nombreiso_ingles='Bermuda', nombreiso_frances='Bermudes (les)', codiso=60 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=60;
      UPDATE sip_pais SET nombreiso_ingles='Paraguay', nombreiso_frances='Paraguay (le)', codiso=600 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=600;
      UPDATE sip_pais SET nombreiso_ingles='Peru', nombreiso_frances='Pérou (le)', codiso=604 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=604;
      UPDATE sip_pais SET nombreiso_ingles='Philippines (the)', nombreiso_frances='Philippines (les)', codiso=608 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=608;
      UPDATE sip_pais SET nombreiso_ingles='Pitcairn', nombreiso_frances='Pitcairn', codiso=612 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=612;
      UPDATE sip_pais SET nombreiso_ingles='Poland', nombreiso_frances='Pologne (la)', codiso=616 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=616;
      UPDATE sip_pais SET nombreiso_ingles='Portugal', nombreiso_frances='Portugal (le)', codiso=620 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=620;
      UPDATE sip_pais SET nombreiso_ingles='Guinea-Bissau', nombreiso_frances='Guinée-Bissau (la)', codiso=624 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=624;
      UPDATE sip_pais SET nombreiso_ingles='Timor-Leste', nombreiso_frances='Timor-Leste (le)', codiso=626 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=626;
      UPDATE sip_pais SET nombreiso_ingles='Puerto Rico', nombreiso_frances='Porto Rico', codiso=630 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=630;
      UPDATE sip_pais SET nombreiso_ingles='Qatar', nombreiso_frances='Qatar (le)', codiso=634 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=634;
      UPDATE sip_pais SET nombreiso_ingles='Réunion', nombreiso_frances='Réunion (La)', codiso=638 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=638;
      UPDATE sip_pais SET nombreiso_ingles='Bhutan', nombreiso_frances='Bhoutan (le)', codiso=64 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=64;
      UPDATE sip_pais SET nombreiso_ingles='Romania', nombreiso_frances='Roumanie (la)', codiso=642 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=642;
      UPDATE sip_pais SET nombreiso_ingles='Russian Federation (the)', nombreiso_frances='Russie (la Fédération de)', codiso=643 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=643;
      UPDATE sip_pais SET nombreiso_ingles='Rwanda', nombreiso_frances='Rwanda (le)', codiso=646 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=646;
      UPDATE sip_pais SET nombreiso_ingles='Saint Barthélemy', nombreiso_frances='Saint-Barthélemy', codiso=652 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=652;
      UPDATE sip_pais SET nombreiso_ingles='Saint Helena, Ascension and Tristan da Cunha', nombreiso_frances='Sainte-Hélène, Ascension et Tristan da Cunha', codiso=654 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=654;
      UPDATE sip_pais SET nombreiso_ingles='Saint Kitts and Nevis', nombreiso_frances='Saint-Kitts-et-Nevis', codiso=659 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=659;
      UPDATE sip_pais SET nombreiso_ingles='Anguilla', nombreiso_frances='Anguilla', codiso=660 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=660;
      UPDATE sip_pais SET nombreiso_ingles='Saint Lucia', nombreiso_frances='Sainte-Lucie', codiso=662 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=662;
      UPDATE sip_pais SET nombreiso_ingles='Saint Martin (French part)', nombreiso_frances='Saint-Martin (partie française)', codiso=663 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=663;
      UPDATE sip_pais SET nombreiso_ingles='Saint Pierre and Miquelon', nombreiso_frances='Saint-Pierre-et-Miquelon', codiso=666 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=666;
      UPDATE sip_pais SET nombreiso_ingles='Saint Vincent and the Grenadines', nombreiso_frances='Saint-Vincent-et-les Grenadines', codiso=670 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=670;
      UPDATE sip_pais SET nombreiso_ingles='San Marino', nombreiso_frances='Saint-Marin', codiso=674 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=674;
      UPDATE sip_pais SET nombreiso_ingles='Sao Tome and Principe', nombreiso_frances='Sao Tomé-et-Principe', codiso=678 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=678;
      UPDATE sip_pais SET nombreiso_ingles='Bolivia (Plurinational State of)', nombreiso_frances='Bolivie (État plurinational de)', codiso=68 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=68;
      UPDATE sip_pais SET nombreiso_ingles='Saudi Arabia', nombreiso_frances='Arabie saoudite (l'')', codiso=682 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=682;
      UPDATE sip_pais SET nombreiso_ingles='Senegal', nombreiso_frances='Sénégal (le)', codiso=686 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=686;
      UPDATE sip_pais SET nombreiso_ingles='Serbia', nombreiso_frances='Serbie (la)', codiso=688 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=688;
      UPDATE sip_pais SET nombreiso_ingles='Seychelles', nombreiso_frances='Seychelles (les)', codiso=690 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=690;
      UPDATE sip_pais SET nombreiso_ingles='Sierra Leone', nombreiso_frances='Sierra Leone (la)', codiso=694 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=694;
      UPDATE sip_pais SET nombreiso_ingles='Bosnia and Herzegovina', nombreiso_frances='Bosnie-Herzégovine (la)', codiso=70 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=70;
      UPDATE sip_pais SET nombreiso_ingles='Singapore', nombreiso_frances='Singapour', codiso=702 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=702;
      UPDATE sip_pais SET nombreiso_ingles='Slovakia', nombreiso_frances='Slovaquie (la)', codiso=703 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=703;
      UPDATE sip_pais SET nombreiso_ingles='Viet Nam', nombreiso_frances='Viet Nam (le)', codiso=704 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=704;
      UPDATE sip_pais SET nombreiso_ingles='Slovenia', nombreiso_frances='Slovénie (la)', codiso=705 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=705;
      UPDATE sip_pais SET nombreiso_ingles='Somalia', nombreiso_frances='Somalie (la)', codiso=706 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=706;
      UPDATE sip_pais SET nombreiso_ingles='South Africa', nombreiso_frances='Afrique du Sud (l'')', codiso=710 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=710;
      UPDATE sip_pais SET nombreiso_ingles='Zimbabwe', nombreiso_frances='Zimbabwe (le)', codiso=716 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=716;
      UPDATE sip_pais SET nombreiso_ingles='Botswana', nombreiso_frances='Botswana (le)', codiso=72 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=72;
      UPDATE sip_pais SET nombreiso_ingles='Spain', nombreiso_frances='Espagne (l'')', codiso=724 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=724;
      UPDATE sip_pais SET nombreiso_ingles='South Sudan', nombreiso_frances='Soudan du Sud (le)', codiso=728 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=728;
      UPDATE sip_pais SET nombreiso_ingles='Sudan (the)', nombreiso_frances='Soudan (le)', codiso=729 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=729;
      UPDATE sip_pais SET nombreiso_ingles='Western Sahara*', nombreiso_frances='Sahara occidental (le)*', codiso=732 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=732;
      UPDATE sip_pais SET nombreiso_ingles='Bouvet Island', nombreiso_frances='Bouvet (l''Île)', codiso=74 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=74;
      UPDATE sip_pais SET nombreiso_ingles='Suriname', nombreiso_frances='Suriname (le)', codiso=740 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=740;
      UPDATE sip_pais SET nombreiso_ingles='Svalbard and Jan Mayen', nombreiso_frances='Svalbard et l''Île Jan Mayen (le)', codiso=744 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=744;
      UPDATE sip_pais SET nombreiso_ingles='Eswatini', nombreiso_frances='Eswatini (l'')', codiso=748 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=748;
      UPDATE sip_pais SET nombreiso_ingles='Sweden', nombreiso_frances='Suède (la)', codiso=752 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=752;
      UPDATE sip_pais SET nombreiso_ingles='Switzerland', nombreiso_frances='Suisse (la)', codiso=756 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=756;
      UPDATE sip_pais SET nombreiso_ingles='Brazil', nombreiso_frances='Brésil (le)', codiso=76 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=76;
      UPDATE sip_pais SET nombreiso_ingles='Syrian Arab Republic (the)', nombreiso_frances='République arabe syrienne (la)', codiso=760 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=760;
      UPDATE sip_pais SET nombreiso_ingles='Tajikistan', nombreiso_frances='Tadjikistan (le)', codiso=762 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=762;
      UPDATE sip_pais SET nombreiso_ingles='Thailand', nombreiso_frances='Thaïlande (la)', codiso=764 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=764;
      UPDATE sip_pais SET nombreiso_ingles='Togo', nombreiso_frances='Togo (le)', codiso=768 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=768;
      UPDATE sip_pais SET nombreiso_ingles='Tokelau', nombreiso_frances='Tokelau (les)', codiso=772 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=772;
      UPDATE sip_pais SET nombreiso_ingles='Tonga', nombreiso_frances='Tonga (les)', codiso=776 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=776;
      UPDATE sip_pais SET nombreiso_ingles='Trinidad and Tobago', nombreiso_frances='Trinité-et-Tobago (la)', codiso=780 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=780;
      UPDATE sip_pais SET nombreiso_ingles='United Arab Emirates (the)', nombreiso_frances='Émirats arabes unis (les)', codiso=784 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=784;
      UPDATE sip_pais SET nombreiso_ingles='Tunisia', nombreiso_frances='Tunisie (la)', codiso=788 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=788;
      UPDATE sip_pais SET nombreiso_ingles='Turkey', nombreiso_frances='Turquie (la)', codiso=792 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=792;
      UPDATE sip_pais SET nombreiso_ingles='Turkmenistan', nombreiso_frances='Turkménistan (le)', codiso=795 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=795;
      UPDATE sip_pais SET nombreiso_ingles='Turks and Caicos Islands (the)', nombreiso_frances='Turks-et-Caïcos (les Îles)', codiso=796 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=796;
      UPDATE sip_pais SET nombreiso_ingles='Tuvalu', nombreiso_frances='Tuvalu (les)', codiso=798 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=798;
      UPDATE sip_pais SET nombreiso_ingles='Albania', nombreiso_frances='Albanie (l'')', codiso=8 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=8;
      UPDATE sip_pais SET nombreiso_ingles='Uganda', nombreiso_frances='Ouganda (l'')', codiso=800 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=800;
      UPDATE sip_pais SET nombreiso_ingles='Ukraine', nombreiso_frances='Ukraine (l'')', codiso=804 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=804;
      UPDATE sip_pais SET nombreiso_ingles='North Macedonia', nombreiso_frances='Macédoine du Nord (la)', codiso=807 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=807;
      UPDATE sip_pais SET nombreiso_ingles='Egypt', nombreiso_frances='Égypte (l'')', codiso=818 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=818;
      UPDATE sip_pais SET nombreiso_ingles='United Kingdom of Great Britain and Northern Ireland (the)', nombreiso_frances='Royaume-Uni de Grande-Bretagne et d''Irlande du Nord (le)', codiso=826 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=826;
      UPDATE sip_pais SET nombreiso_ingles='Guernsey', nombreiso_frances='Guernesey', codiso=831 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=831;
      UPDATE sip_pais SET nombreiso_ingles='Jersey', nombreiso_frances='Jersey', codiso=832 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=832;
      UPDATE sip_pais SET nombreiso_ingles='Isle of Man', nombreiso_frances='Île de Man', codiso=833 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=833;
      UPDATE sip_pais SET nombreiso_ingles='Tanzania, the United Republic of', nombreiso_frances='Tanzanie (la République-Unie de)', codiso=834 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=834;
      UPDATE sip_pais SET nombreiso_ingles='Belize', nombreiso_frances='Belize (le)', codiso=84 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=84;
      UPDATE sip_pais SET nombreiso_ingles='United States of America (the)', nombreiso_frances='États-Unis d''Amérique (les)', codiso=840 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=840;
      UPDATE sip_pais SET nombreiso_ingles='Virgin Islands (U.S.)', nombreiso_frances='Vierges des États-Unis (les Îles)', codiso=850 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=850;
      UPDATE sip_pais SET nombreiso_ingles='Burkina Faso', nombreiso_frances='Burkina Faso (le)', codiso=854 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=854;
      UPDATE sip_pais SET nombreiso_ingles='Uruguay', nombreiso_frances='Uruguay (l'')', codiso=858 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=858;
      UPDATE sip_pais SET nombreiso_ingles='British Indian Ocean Territory (the)', nombreiso_frances='Indien (le Territoire britannique de l''océan)', codiso=86 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=86;
      UPDATE sip_pais SET nombreiso_ingles='Uzbekistan', nombreiso_frances='Ouzbékistan (l'')', codiso=860 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=860;
      UPDATE sip_pais SET nombreiso_ingles='Venezuela (Bolivarian Republic of)', nombreiso_frances='Venezuela (République bolivarienne du)', codiso=862 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=862;
      UPDATE sip_pais SET nombreiso_ingles='Samoa', nombreiso_frances='Samoa (le)', codiso=882 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=882;
      UPDATE sip_pais SET nombreiso_ingles='Yemen', nombreiso_frances='Yémen (le)', codiso=887 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=887;
      UPDATE sip_pais SET nombreiso_ingles='Zambia', nombreiso_frances='Zambie (la)', codiso=894 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=894;
      UPDATE sip_pais SET nombreiso_ingles='Solomon Islands', nombreiso_frances='Salomon (les Îles)', codiso=90 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=90;
      UPDATE sip_pais SET nombreiso_ingles='Virgin Islands (British)', nombreiso_frances='Vierges britanniques (les Îles)', codiso=92 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=92;
      UPDATE sip_pais SET nombreiso_ingles='Brunei Darussalam', nombreiso_frances='Brunéi Darussalam (le)', codiso=96 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=96;
      UPDATE sip_pais SET nombreiso_ingles='Wallis and Futuna', nombreiso_frances='Wallis-et-Futuna', codiso=876 , observaciones='Nombres en inglés y francés de iso.org' WHERE id=876;
    SQL
  end

  def down
    execute <<-SQL
      DELETE FROM sip_pais WHERE id='876';
    SQL
    remove_column :sip_pais, :nombreiso_frances
    remove_column :sip_pais, :nombreiso_ingles
    rename_column :sip_pais, :nombreosm, :nombreiso
  end
end
