class PaisAltasbajas < ActiveRecord::Migration[7.0]
  def up
    execute <<-SQL
      UPDATE sip_pais SET nombre='Afganistán', nombreiso_espanol='Afganistán', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=4;
      UPDATE sip_pais SET nombre='Åland', nombreiso_espanol='Åland, Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=248;
      UPDATE sip_pais SET nombre='Albania', nombreiso_espanol='Albania', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=8;
      UPDATE sip_pais SET nombre='Alemania', nombreiso_espanol='Alemania', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=276;
      UPDATE sip_pais SET nombre='Andorra', nombreiso_espanol='Andorra', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=20;
      UPDATE sip_pais SET nombre='Angola', nombreiso_espanol='Angola', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=24;
      UPDATE sip_pais SET nombre='Anguila', nombreiso_espanol='Anguila', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=660;
      UPDATE sip_pais SET nombre='Antártida', nombreiso_espanol='Antártida', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=10;
      UPDATE sip_pais SET nombre='Antigua y Barbuda', nombreiso_espanol='Antigua y Barbuda', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=28;
      UPDATE sip_pais SET nombre='Arabia Saudita', nombreiso_espanol='Arabia Saudita', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=682;
      UPDATE sip_pais SET nombre='Argelia', nombreiso_espanol='Argelia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=12;
      UPDATE sip_pais SET nombre='Argentina', nombreiso_espanol='Argentina', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=32;
      UPDATE sip_pais SET nombre='Armenia', nombreiso_espanol='Armenia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=51;
      UPDATE sip_pais SET nombre='Aruba', nombreiso_espanol='Aruba', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=533;
      UPDATE sip_pais SET nombre='Australia', nombreiso_espanol='Australia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=36;
      UPDATE sip_pais SET nombre='Austria', nombreiso_espanol='Austria', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=40;
      UPDATE sip_pais SET nombre='Azerbaiyán', nombreiso_espanol='Azerbaiyán', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=31;
      UPDATE sip_pais SET nombre='Bahamas', nombreiso_espanol='Bahamas (las)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=44;
      UPDATE sip_pais SET nombre='Bangladés', nombreiso_espanol='Bangladés', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=50;
      UPDATE sip_pais SET nombre='Barbados', nombreiso_espanol='Barbados', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=52;
      UPDATE sip_pais SET nombre='Baréin', nombreiso_espanol='Baréin', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=48;
      UPDATE sip_pais SET nombre='Bélgica', nombreiso_espanol='Bélgica', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=56;
      UPDATE sip_pais SET nombre='Belice', nombreiso_espanol='Belice', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=84;
      UPDATE sip_pais SET nombre='Benín', nombreiso_espanol='Benín', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=204;
      UPDATE sip_pais SET nombre='Bermudas', nombreiso_espanol='Bermudas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=60;
      UPDATE sip_pais SET nombre='Bielorrusia', nombreiso_espanol='Belarús', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=112;
      UPDATE sip_pais SET nombre='Birmania', nombreiso_espanol='Myanmar', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=104;
      UPDATE sip_pais SET nombre='Bolivia', nombreiso_espanol='Bolivia (Estado Plurinacional de)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=68;
      UPDATE sip_pais SET nombre='Bosnia y Herzegovina', nombreiso_espanol='Bosnia y Herzegovina', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=70;
      UPDATE sip_pais SET nombre='Botsuana', nombreiso_espanol='Botsuana', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=72;
      UPDATE sip_pais SET nombre='Brasil', nombreiso_espanol='Brasil', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=76;
      UPDATE sip_pais SET nombre='Brunéi', nombreiso_espanol='Brunéi Darussalam', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=96;
      UPDATE sip_pais SET nombre='Bulgaria', nombreiso_espanol='Bulgaria', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=100;
      UPDATE sip_pais SET nombre='Burkina Faso', nombreiso_espanol='Burkina Faso', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=854;
      UPDATE sip_pais SET nombre='Burundi', nombreiso_espanol='Burundi', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=108;
      UPDATE sip_pais SET nombre='Bután', nombreiso_espanol='Bhután', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=64;
      UPDATE sip_pais SET nombre='Cabo Verde', nombreiso_espanol='Cabo Verde', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=132;
      UPDATE sip_pais SET nombre='Camboya', nombreiso_espanol='Camboya', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=116;
      UPDATE sip_pais SET nombre='Camerún', nombreiso_espanol='Camerún', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=120;
      UPDATE sip_pais SET nombre='Canadá', nombreiso_espanol='Canadá', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=124;
      UPDATE sip_pais SET nombre='Bonaire, San Eustaquio y Saba', nombreiso_espanol='Bonaire, San Eustaquio y Saba', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=535;
      UPDATE sip_pais SET nombre='Catar', nombreiso_espanol='Qatar', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=634;
      UPDATE sip_pais SET nombre='Chad', nombreiso_espanol='Chad', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=148;
      UPDATE sip_pais SET nombre='Chile', nombreiso_espanol='Chile', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=152;
      UPDATE sip_pais SET nombre='China', nombreiso_espanol='China', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=156;
      UPDATE sip_pais SET nombre='Chipre', nombreiso_espanol='Chipre', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=196;
      UPDATE sip_pais SET nombre='Ciudad del Vaticano', nombreiso_espanol='Santa Sede (la)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=336;
      UPDATE sip_pais SET nombre='Colombia', nombreiso_espanol='Colombia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=170;
      UPDATE sip_pais SET nombre='Comoras', nombreiso_espanol='Comoras (las)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=174;
      UPDATE sip_pais SET nombre='Corea del Norte', nombreiso_espanol='Corea (la República Popular Democrática de)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=408;
      UPDATE sip_pais SET nombre='Corea del Sur', nombreiso_espanol='Corea (la República de)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=410;
      UPDATE sip_pais SET nombre='Costa de Marfil', nombreiso_espanol='Côte d''Ivoire', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=384;
      UPDATE sip_pais SET nombre='Costa Rica', nombreiso_espanol='Costa Rica', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=188;
      UPDATE sip_pais SET nombre='Croacia', nombreiso_espanol='Croacia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=191;
      UPDATE sip_pais SET nombre='Cuba', nombreiso_espanol='Cuba', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=192;
      UPDATE sip_pais SET nombre='Curazao', nombreiso_espanol='Curaçao', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=531;
      UPDATE sip_pais SET nombre='Dinamarca', nombreiso_espanol='Dinamarca', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=208;
      UPDATE sip_pais SET nombre='Dominica', nombreiso_espanol='Dominica', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=212;
      UPDATE sip_pais SET nombre='Ecuador', nombreiso_espanol='Ecuador', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=218;
      UPDATE sip_pais SET nombre='Egipto', nombreiso_espanol='Egipto', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=818;
      UPDATE sip_pais SET nombre='El Salvador', nombreiso_espanol='El Salvador', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=222;
      UPDATE sip_pais SET nombre='Emiratos Árabes Unidos', nombreiso_espanol='Emiratos Árabes Unidos (los)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=784;
      UPDATE sip_pais SET nombre='Eritrea', nombreiso_espanol='Eritrea', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=232;
      UPDATE sip_pais SET nombre='Eslovaquia', nombreiso_espanol='Eslovaquia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=703;
      UPDATE sip_pais SET nombre='Eslovenia', nombreiso_espanol='Eslovenia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=705;
      UPDATE sip_pais SET nombre='España', nombreiso_espanol='España', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=724;
      UPDATE sip_pais SET nombre='Palestina', nombreiso_espanol='Palestina, Estado de', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=275;
      UPDATE sip_pais SET nombre='Estados Unidos', nombreiso_espanol='Estados Unidos de América (los)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=840;
      UPDATE sip_pais SET nombre='Estonia', nombreiso_espanol='Estonia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=233;
      UPDATE sip_pais SET nombre='Etiopía', nombreiso_espanol='Etiopía', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=231;
      UPDATE sip_pais SET nombre='Filipinas', nombreiso_espanol='Filipinas (las)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=608;
      UPDATE sip_pais SET nombre='Finlandia', nombreiso_espanol='Finlandia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=246;
      UPDATE sip_pais SET nombre='Fiyi', nombreiso_espanol='Fiji', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=242;
      UPDATE sip_pais SET nombre='Francia', nombreiso_espanol='Francia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=250;
      UPDATE sip_pais SET nombre='Gabón', nombreiso_espanol='Gabón', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=266;
      UPDATE sip_pais SET nombre='Gambia', nombreiso_espanol='Gambia (la)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=270;
      UPDATE sip_pais SET nombre='Georgia', nombreiso_espanol='Georgia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=268;
      UPDATE sip_pais SET nombre='Ghana', nombreiso_espanol='Ghana', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=288;
      UPDATE sip_pais SET nombre='Gibraltar', nombreiso_espanol='Gibraltar', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=292;
      UPDATE sip_pais SET nombre='Granada', nombreiso_espanol='Granada', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=308;
      UPDATE sip_pais SET nombre='Grecia', nombreiso_espanol='Grecia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=300;
      UPDATE sip_pais SET nombre='Groenlandia', nombreiso_espanol='Groenlandia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=304;
      UPDATE sip_pais SET nombre='Guadalupe', nombreiso_espanol='Guadeloupe', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=312;
      UPDATE sip_pais SET nombre='Guam', nombreiso_espanol='Guam', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=316;
      UPDATE sip_pais SET nombre='Guatemala', nombreiso_espanol='Guatemala', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=320;
      UPDATE sip_pais SET nombre='Guayana Francesa', nombreiso_espanol='Guayana Francesa', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=254;
      UPDATE sip_pais SET nombre='Guernsey', nombreiso_espanol='Guernsey', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=831;
      UPDATE sip_pais SET nombre='Guinea', nombreiso_espanol='Guinea', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=324;
      UPDATE sip_pais SET nombre='Guinea Ecuatorial', nombreiso_espanol='Guinea Ecuatorial', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=226;
      UPDATE sip_pais SET nombre='Guinea-Bisáu', nombreiso_espanol='Guinea Bissau', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=624;
      UPDATE sip_pais SET nombre='Guyana', nombreiso_espanol='Guyana', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=328;
      UPDATE sip_pais SET nombre='Haití', nombreiso_espanol='Haití', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=332;
      UPDATE sip_pais SET nombre='Honduras', nombreiso_espanol='Honduras', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=340;
      UPDATE sip_pais SET nombre='Hong Kong', nombreiso_espanol='Hong Kong', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=344;
      UPDATE sip_pais SET nombre='Hungría', nombreiso_espanol='Hungría', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=348;
      UPDATE sip_pais SET nombre='India', nombreiso_espanol='India', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=356;
      UPDATE sip_pais SET nombre='Indonesia', nombreiso_espanol='Indonesia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=360;
      UPDATE sip_pais SET nombre='Irak', nombreiso_espanol='Irak', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=368;
      UPDATE sip_pais SET nombre='Irán', nombreiso_espanol='Irán (República Islámica de)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=364;
      UPDATE sip_pais SET nombre='Irlanda', nombreiso_espanol='Irlanda', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=372;
      UPDATE sip_pais SET nombre='Isla Bouvet', nombreiso_espanol='Bouvet, Isla', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=74;
      UPDATE sip_pais SET nombre='Isla de Man', nombreiso_espanol='Isla de Man', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=833;
      UPDATE sip_pais SET nombre='Isla de Navidad', nombreiso_espanol='Navidad, Isla de', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=162;
      UPDATE sip_pais SET nombre='Islandia', nombreiso_espanol='Islandia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=352;
      UPDATE sip_pais SET nombre='Islas Caimán', nombreiso_espanol='Caimán, (las) Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=136;
      UPDATE sip_pais SET nombre='Islas Cocos', nombreiso_espanol='Cocos / Keeling, (las) Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=166;
      UPDATE sip_pais SET nombre='Islas Cook', nombreiso_espanol='Cook, (las) Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=184;
      UPDATE sip_pais SET nombre='Islas Feroe', nombreiso_espanol='Feroe, (las) Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=234;
      UPDATE sip_pais SET nombre='Islas Georgias del Sur y Sandwich del Sur', nombreiso_espanol='Georgia del Sur (la) y las Islas Sandwich del Sur', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=239;
      UPDATE sip_pais SET nombre='Islas Heard y McDonald', nombreiso_espanol='Heard (Isla) e Islas McDonald', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=334;
      UPDATE sip_pais SET nombre='Islas Malvinas', nombreiso_espanol='Malvinas [Falkland], (las) Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=238;
      UPDATE sip_pais SET nombre='Islas Marianas del Norte', nombreiso_espanol='Marianas del Norte, (las) Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=580;
      UPDATE sip_pais SET nombre='Islas Marshall', nombreiso_espanol='Marshall, (las) Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=584;
      UPDATE sip_pais SET nombre='Islas Pitcairn', nombreiso_espanol='Pitcairn', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=612;
      UPDATE sip_pais SET nombre='Islas Salomón', nombreiso_espanol='Salomón, Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=90;
      UPDATE sip_pais SET nombre='Islas Turcas y Caicos', nombreiso_espanol='Turcas y Caicos, (las) Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=796;
      UPDATE sip_pais SET nombre='Islas Ultramarinas Menores de los Estados Unidos', nombreiso_espanol='Islas Ultramarinas Menores de los Estados Unidos (las)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=581;
      UPDATE sip_pais SET nombre='Islas Vírgenes Británicas', nombreiso_espanol='Vírgenes británicas, Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=92;
      UPDATE sip_pais SET nombre='Islas Vírgenes de los Estados Unidos', nombreiso_espanol='Vírgenes de los Estados Unidos, Islas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=850;
      UPDATE sip_pais SET nombre='Israel', nombreiso_espanol='Israel', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=376;
      UPDATE sip_pais SET nombre='Italia', nombreiso_espanol='Italia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=380;
      UPDATE sip_pais SET nombre='Jamaica', nombreiso_espanol='Jamaica', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=388;
      UPDATE sip_pais SET nombre='Japón', nombreiso_espanol='Japón', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=392;
      UPDATE sip_pais SET nombre='Jersey', nombreiso_espanol='Jersey', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=832;
      UPDATE sip_pais SET nombre='Jordania', nombreiso_espanol='Jordania', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=400;
      UPDATE sip_pais SET nombre='Kazajistán', nombreiso_espanol='Kazajistán', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=398;
      UPDATE sip_pais SET nombre='Kenia', nombreiso_espanol='Kenia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=404;
      UPDATE sip_pais SET nombre='Kirguistán', nombreiso_espanol='Kirguistán', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=417;
      UPDATE sip_pais SET nombre='Kiribati', nombreiso_espanol='Kiribati', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=296;
      UPDATE sip_pais SET nombre='Kuwait', nombreiso_espanol='Kuwait', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=414;
      UPDATE sip_pais SET nombre='Laos', nombreiso_espanol='Lao, (la) República Democrática Popular', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=418;
      UPDATE sip_pais SET nombre='Lesoto', nombreiso_espanol='Lesoto', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=426;
      UPDATE sip_pais SET nombre='Letonia', nombreiso_espanol='Letonia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=428;
      UPDATE sip_pais SET nombre='Líbano', nombreiso_espanol='Líbano', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=422;
      UPDATE sip_pais SET nombre='Liberia', nombreiso_espanol='Liberia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=430;
      UPDATE sip_pais SET nombre='Libia', nombreiso_espanol='Libia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=434;
      UPDATE sip_pais SET nombre='Liechtenstein', nombreiso_espanol='Liechtenstein', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=438;
      UPDATE sip_pais SET nombre='Lituania', nombreiso_espanol='Lituania', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=440;
      UPDATE sip_pais SET nombre='Luxemburgo', nombreiso_espanol='Luxemburgo', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=442;
      UPDATE sip_pais SET nombre='Macao', nombreiso_espanol='Macao', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=446;
      UPDATE sip_pais SET nombre='Madagascar', nombreiso_espanol='Madagascar', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=450;
      UPDATE sip_pais SET nombre='Malasia', nombreiso_espanol='Malasia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=458;
      UPDATE sip_pais SET nombre='Malaui', nombreiso_espanol='Malawi', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=454;
      UPDATE sip_pais SET nombre='Maldivas', nombreiso_espanol='Maldivas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=462;
      UPDATE sip_pais SET nombre='Malí', nombreiso_espanol='Malí', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=466;
      UPDATE sip_pais SET nombre='Malta', nombreiso_espanol='Malta', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=470;
      UPDATE sip_pais SET nombre='Marruecos', nombreiso_espanol='Marruecos', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=504;
      UPDATE sip_pais SET nombre='Martinica', nombreiso_espanol='Martinique', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=474;
      UPDATE sip_pais SET nombre='Mauricio', nombreiso_espanol='Mauricio', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=480;
      UPDATE sip_pais SET nombre='Mauritania', nombreiso_espanol='Mauritania', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=478;
      UPDATE sip_pais SET nombre='Mayotte', nombreiso_espanol='Mayotte', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=175;
      UPDATE sip_pais SET nombre='México', nombreiso_espanol='México', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=484;
      UPDATE sip_pais SET nombre='Micronesia', nombreiso_espanol='Micronesia (Estados Federados de)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=583;
      UPDATE sip_pais SET nombre='Moldavia', nombreiso_espanol='Moldova (la República de)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=498;
      UPDATE sip_pais SET nombre='Mónaco', nombreiso_espanol='Mónaco', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=492;
      UPDATE sip_pais SET nombre='Mongolia', nombreiso_espanol='Mongolia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=496;
      UPDATE sip_pais SET nombre='Montenegro', nombreiso_espanol='Montenegro', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=499;
      UPDATE sip_pais SET nombre='Montserrat', nombreiso_espanol='Montserrat', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=500;
      UPDATE sip_pais SET nombre='Mozambique', nombreiso_espanol='Mozambique', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=508;
      UPDATE sip_pais SET nombre='Namibia', nombreiso_espanol='Namibia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=516;
      UPDATE sip_pais SET nombre='Nauru', nombreiso_espanol='Nauru', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=520;
      UPDATE sip_pais SET nombre='Nepal', nombreiso_espanol='Nepal', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=524;
      UPDATE sip_pais SET nombre='Nicaragua', nombreiso_espanol='Nicaragua', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=558;
      UPDATE sip_pais SET nombre='Níger', nombreiso_espanol='Níger (el)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=562;
      UPDATE sip_pais SET nombre='Nigeria', nombreiso_espanol='Nigeria', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=566;
      UPDATE sip_pais SET nombre='Niue', nombreiso_espanol='Niue', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=570;
      UPDATE sip_pais SET nombre='Isla Norfolk', nombreiso_espanol='Norfolk, Isla', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=574;
      UPDATE sip_pais SET nombre='Noruega', nombreiso_espanol='Noruega', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=578;
      UPDATE sip_pais SET nombre='Nueva Caledonia', nombreiso_espanol='Nueva Caledonia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=540;
      UPDATE sip_pais SET nombre='Nueva Zelanda', nombreiso_espanol='Nueva Zelandia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=554;
      UPDATE sip_pais SET nombre='Omán', nombreiso_espanol='Omán', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=512;
      UPDATE sip_pais SET nombre='Países Bajos', nombreiso_espanol='Países Bajos (los)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=528;
      UPDATE sip_pais SET nombre='Pakistán', nombreiso_espanol='Pakistán', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=586;
      UPDATE sip_pais SET nombre='Palaos', nombreiso_espanol='Palau', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=585;
      UPDATE sip_pais SET nombre='Panamá', nombreiso_espanol='Panamá', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=591;
      UPDATE sip_pais SET nombre='Papúa Nueva Guinea', nombreiso_espanol='Papua Nueva Guinea', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=598;
      UPDATE sip_pais SET nombre='Paraguay', nombreiso_espanol='Paraguay', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=600;
      UPDATE sip_pais SET nombre='Perú', nombreiso_espanol='Perú', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=604;
      UPDATE sip_pais SET nombre='Polinesia Francesa', nombreiso_espanol='Polinesia Francesa', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=258;
      UPDATE sip_pais SET nombre='Polonia', nombreiso_espanol='Polonia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=616;
      UPDATE sip_pais SET nombre='Portugal', nombreiso_espanol='Portugal', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=620;
      UPDATE sip_pais SET nombre='Puerto Rico', nombreiso_espanol='Puerto Rico', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=630;
      UPDATE sip_pais SET nombre='Reino Unido', nombreiso_espanol='Reino Unido de Gran Bretaña e Irlanda del Norte (el)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=826;
      UPDATE sip_pais SET nombre='República Centroafricana', nombreiso_espanol='República Centroafricana (la)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=140;
      UPDATE sip_pais SET nombre='República Checa', nombreiso_espanol='Chequia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=203;
      UPDATE sip_pais SET nombre='Macedonia del Norte', nombreiso_espanol='Macedonia del Norte', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=807;
      UPDATE sip_pais SET nombre='República del Congo', nombreiso_espanol='Congo (el)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=178;
      UPDATE sip_pais SET nombre='República Democrática del Congo', nombreiso_espanol='Congo (la República Democrática del)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=180;
      UPDATE sip_pais SET nombre='República Dominicana', nombreiso_espanol='Dominicana, (la) República', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=214;
      UPDATE sip_pais SET nombre='Reunión', nombreiso_espanol='Reunión', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=638;
      UPDATE sip_pais SET nombre='Ruanda', nombreiso_espanol='Ruanda', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=646;
      UPDATE sip_pais SET nombre='Rumania', nombreiso_espanol='Rumania', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=642;
      UPDATE sip_pais SET nombre='Rusia', nombreiso_espanol='Rusia, (la) Federación de', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=643;
      UPDATE sip_pais SET nombre='República Árabe Saharaui Democrática', nombreiso_espanol='Sahara Occidental', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=732;
      UPDATE sip_pais SET nombre='Samoa', nombreiso_espanol='Samoa', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=882;
      UPDATE sip_pais SET nombre='Samoa Americana', nombreiso_espanol='Samoa Americana', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=16;
      UPDATE sip_pais SET nombre='San Bartolomé', nombreiso_espanol='Saint Barthélemy', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=652;
      UPDATE sip_pais SET nombre='San Cristóbal y Nieves', nombreiso_espanol='San Cristóbal y Nieves', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=659;
      UPDATE sip_pais SET nombre='San Marino', nombreiso_espanol='San Marino', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=674;
      UPDATE sip_pais SET nombre='San Martín', nombreiso_espanol='Saint Martin (parte francesa)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=663;
      UPDATE sip_pais SET nombre='San Pedro y Miquelón', nombreiso_espanol='San Pedro y Miquelón', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=666;
      UPDATE sip_pais SET nombre='San Vicente y las Granadinas', nombreiso_espanol='San Vicente y las Granadinas', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=670;
      UPDATE sip_pais SET nombre='Santa Elena, Ascensión y Tristán de Acuña', nombreiso_espanol='Santa Helena, Ascensión y Tristán de Acuña', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=654;
      UPDATE sip_pais SET nombre='Santa Lucía', nombreiso_espanol='Santa Lucía', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=662;
      UPDATE sip_pais SET nombre='Santo Tomé y Príncipe', nombreiso_espanol='Santo Tomé y Príncipe', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=678;
      UPDATE sip_pais SET nombre='Senegal', nombreiso_espanol='Senegal', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=686;
      UPDATE sip_pais SET nombre='Serbia', nombreiso_espanol='Serbia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=688;
      UPDATE sip_pais SET nombre='Seychelles', nombreiso_espanol='Seychelles', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=690;
      UPDATE sip_pais SET nombre='Sierra Leona', nombreiso_espanol='Sierra leona', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=694;
      UPDATE sip_pais SET nombre='Singapur', nombreiso_espanol='Singapur', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=702;
      UPDATE sip_pais SET nombre='San Martín', nombreiso_espanol='Sint Maarten (parte neerlandesa)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=534;
      UPDATE sip_pais SET nombre='Siria', nombreiso_espanol='República Árabe Siria', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=760;
      UPDATE sip_pais SET nombre='Somalia', nombreiso_espanol='Somalia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=706;
      UPDATE sip_pais SET nombre='Sri Lanka', nombreiso_espanol='Sri Lanka', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=144;
      UPDATE sip_pais SET nombre='Suazilandia', nombreiso_espanol='Suazilandia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=748;
      UPDATE sip_pais SET nombre='Sudáfrica', nombreiso_espanol='Sudáfrica', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=710;
      UPDATE sip_pais SET nombre='Sudán', nombreiso_espanol='Sudán (el)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=729;
      UPDATE sip_pais SET nombre='Sudán del Sur', nombreiso_espanol='Sudán del Sur', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=728;
      UPDATE sip_pais SET nombre='Suecia', nombreiso_espanol='Suecia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=752;
      UPDATE sip_pais SET nombre='Suiza', nombreiso_espanol='Suiza', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=756;
      UPDATE sip_pais SET nombre='Surinam', nombreiso_espanol='Suriname', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=740;
      UPDATE sip_pais SET nombre='Svalbard y Jan Mayen', nombreiso_espanol='Svalbard y Jan Mayen', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=744;
      UPDATE sip_pais SET nombre='Tailandia', nombreiso_espanol='Tailandia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=764;
      UPDATE sip_pais SET nombre='Taiwán (República de China)', nombreiso_espanol='Taiwán (Provincia de China)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=158;
      UPDATE sip_pais SET nombre='Tanzania', nombreiso_espanol='Tanzania, República Unida de', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=834;
      UPDATE sip_pais SET nombre='Tayikistán', nombreiso_espanol='Tayikistán', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=762;
      UPDATE sip_pais SET nombre='Territorio Británico del Océano Índico', nombreiso_espanol='Territorio Británico del Océano Índico (el)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=86;
      UPDATE sip_pais SET nombre='Tierras Australes y Antárticas Francesas', nombreiso_espanol='Tierras Australes Francesas (las)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=260;
      UPDATE sip_pais SET nombre='Timor Oriental', nombreiso_espanol='Timor-Leste', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=626;
      UPDATE sip_pais SET nombre='Togo', nombreiso_espanol='Togo', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=768;
      UPDATE sip_pais SET nombre='Tokelau', nombreiso_espanol='Tokelau', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=772;
      UPDATE sip_pais SET nombre='Tonga', nombreiso_espanol='Tonga', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=776;
      UPDATE sip_pais SET nombre='Trinidad y Tobago', nombreiso_espanol='Trinidad y Tobago', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=780;
      UPDATE sip_pais SET nombre='Túnez', nombreiso_espanol='Túnez', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=788;
      UPDATE sip_pais SET nombre='Turkmenistán', nombreiso_espanol='Turkmenistán', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=795;
      UPDATE sip_pais SET nombre='Turquía', nombreiso_espanol='Turquía', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=792;
      UPDATE sip_pais SET nombre='Tuvalu', nombreiso_espanol='Tuvalu', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=798;
      UPDATE sip_pais SET nombre='Ucrania', nombreiso_espanol='Ucrania', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=804;
      UPDATE sip_pais SET nombre='Uganda', nombreiso_espanol='Uganda', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=800;
      UPDATE sip_pais SET nombre='Uruguay', nombreiso_espanol='Uruguay', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=858;
      UPDATE sip_pais SET nombre='Uzbekistán', nombreiso_espanol='Uzbekistán', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=860;
      UPDATE sip_pais SET nombre='Vanuatu', nombreiso_espanol='Vanuatu', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=548;
      UPDATE sip_pais SET nombre='Venezuela', nombreiso_espanol='Venezuela (República Bolivariana de)', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=862;
      UPDATE sip_pais SET nombre='Vietnam', nombreiso_espanol='Viet Nam', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=704;
      UPDATE sip_pais SET nombre='Wallis y Futuna', nombreiso_espanol='Wallis y Futuna', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=876;
      UPDATE sip_pais SET nombre='Yemen', nombreiso_espanol='Yemen', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=887;
      UPDATE sip_pais SET nombre='Yibuti', nombreiso_espanol='Yibuti', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=262;
      UPDATE sip_pais SET nombre='Zambia', nombreiso_espanol='Zambia', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=894;
      UPDATE sip_pais SET nombre='Zimbabue', nombreiso_espanol='Zimbabue', observaciones = observaciones || '  Nombre en esp. y nombre iso en esp de https://es.wikipedia.org/wiki/ISO_3166-1.' where id=716;
    SQL
  end
  def down
    execute <<-SQL
      UPDATE sip_pais SET nombre='AFGANISTÁN', nombreiso_espanol='AFGANISTAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=4;
      UPDATE sip_pais SET nombre='ÅLAND', nombreiso_espanol='ISLAS ÅLAND', observaciones = 'Nombres en inglés y francés de iso.org' where id=248;
      UPDATE sip_pais SET nombre='ALBANIA', nombreiso_espanol='ALBANIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=8;
      UPDATE sip_pais SET nombre='ALEMANIA', nombreiso_espanol='ALEMANIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=276;
      UPDATE sip_pais SET nombre='ANDORRA', nombreiso_espanol='ANDORRA', observaciones = 'Nombres en inglés y francés de iso.org' where id=20;
      UPDATE sip_pais SET nombre='ANGOLA', nombreiso_espanol='ANGOLA', observaciones = 'Nombres en inglés y francés de iso.org' where id=24;
      UPDATE sip_pais SET nombre='ANGUILA', nombreiso_espanol='ANGUILA', observaciones = 'Nombres en inglés y francés de iso.org' where id=660;
      UPDATE sip_pais SET nombre='ANTÁRTIDA', nombreiso_espanol='ANTARTIDA', observaciones = 'Nombres en inglés y francés de iso.org' where id=10;
      UPDATE sip_pais SET nombre='ANTIGUA Y BARBUDA', nombreiso_espanol='ANTIGUA Y BARBUDA', observaciones = 'Nombres en inglés y francés de iso.org' where id=28;
      UPDATE sip_pais SET nombre='ARABIA SAUDITA', nombreiso_espanol='ARABIA SAUDITA', observaciones = 'Nombres en inglés y francés de iso.org' where id=682;
      UPDATE sip_pais SET nombre='ARGELIA', nombreiso_espanol='ARGELIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=12;
      UPDATE sip_pais SET nombre='ARGENTINA', nombreiso_espanol='ARGENTINA', observaciones = 'Nombres en inglés y francés de iso.org' where id=32;
      UPDATE sip_pais SET nombre='ARMENIA', nombreiso_espanol='ARMENIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=51;
      UPDATE sip_pais SET nombre='ARUBA', nombreiso_espanol='ARUBA', observaciones = 'Nombres en inglés y francés de iso.org' where id=533;
      UPDATE sip_pais SET nombre='AUSTRALIA', nombreiso_espanol='AUSTRALIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=36;
      UPDATE sip_pais SET nombre='AUSTRIA', nombreiso_espanol='AUSTRIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=40;
      UPDATE sip_pais SET nombre='AZERBAIYÁN', nombreiso_espanol='AZERBAIYAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=31;
      UPDATE sip_pais SET nombre='BAHAMAS', nombreiso_espanol='BAHAMAS', observaciones = 'Nombres en inglés y francés de iso.org' where id=44;
      UPDATE sip_pais SET nombre='BANGLADÉS', nombreiso_espanol='BANGLADES', observaciones = 'Nombres en inglés y francés de iso.org' where id=50;
      UPDATE sip_pais SET nombre='BARBADOS', nombreiso_espanol='BARBADOS', observaciones = 'Nombres en inglés y francés de iso.org' where id=52;
      UPDATE sip_pais SET nombre='BARÉIN', nombreiso_espanol='BAREIN', observaciones = 'Nombres en inglés y francés de iso.org' where id=48;
      UPDATE sip_pais SET nombre='BÉLGICA', nombreiso_espanol='BELGICA', observaciones = 'Nombres en inglés y francés de iso.org' where id=56;
      UPDATE sip_pais SET nombre='BELICE', nombreiso_espanol='BELICE', observaciones = 'Nombres en inglés y francés de iso.org' where id=84;
      UPDATE sip_pais SET nombre='BENÍN', nombreiso_espanol='BENIN', observaciones = 'Nombres en inglés y francés de iso.org' where id=204;
      UPDATE sip_pais SET nombre='BERMUDAS', nombreiso_espanol='BERMUDAS', observaciones = 'Nombres en inglés y francés de iso.org' where id=60;
      UPDATE sip_pais SET nombre='BIELORRUSIA', nombreiso_espanol='BIELORRUSIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=112;
      UPDATE sip_pais SET nombre='BIRMANIA', nombreiso_espanol='MYANMAR', observaciones = 'Nombres en inglés y francés de iso.org' where id=104;
      UPDATE sip_pais SET nombre='BOLIVIA', nombreiso_espanol='BOLIVIA, ESTADO PLURINACIONAL DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=68;
      UPDATE sip_pais SET nombre='BOSNIA Y HERZEGOVINA', nombreiso_espanol='BOSNIA Y HERZEGOVINA', observaciones = 'Nombres en inglés y francés de iso.org' where id=70;
      UPDATE sip_pais SET nombre='BOTSUANA', nombreiso_espanol='BOTSUANA', observaciones = 'Nombres en inglés y francés de iso.org' where id=72;
      UPDATE sip_pais SET nombre='BRASIL', nombreiso_espanol='BRASIL', observaciones = 'Nombres en inglés y francés de iso.org' where id=76;
      UPDATE sip_pais SET nombre='BRUNÉI', nombreiso_espanol='BRUNEI DARUSSALAM', observaciones = 'Nombres en inglés y francés de iso.org' where id=96;
      UPDATE sip_pais SET nombre='BULGARIA', nombreiso_espanol='BULGARIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=100;
      UPDATE sip_pais SET nombre='BURKINA FASO', nombreiso_espanol='BURKINA FASO', observaciones = 'Nombres en inglés y francés de iso.org' where id=854;
      UPDATE sip_pais SET nombre='BURUNDI', nombreiso_espanol='BURUNDI', observaciones = 'Nombres en inglés y francés de iso.org' where id=108;
      UPDATE sip_pais SET nombre='BUTÁN', nombreiso_espanol='BUTAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=64;
      UPDATE sip_pais SET nombre='CABO VERDE', nombreiso_espanol='CABO VERDE', observaciones = 'Nombres en inglés y francés de iso.org' where id=132;
      UPDATE sip_pais SET nombre='CAMBOYA', nombreiso_espanol='CAMBOYA', observaciones = 'Nombres en inglés y francés de iso.org' where id=116;
      UPDATE sip_pais SET nombre='CAMERÚN', nombreiso_espanol='CAMERUN', observaciones = 'Nombres en inglés y francés de iso.org' where id=120;
      UPDATE sip_pais SET nombre='CANADÁ', nombreiso_espanol='CANADA', observaciones = 'Nombres en inglés y francés de iso.org' where id=124;
      UPDATE sip_pais SET nombre='CARIBE NEERLANDÉS', nombreiso_espanol='BONAIRE, SAN EUSTAQUIO Y SABA', observaciones = 'Nombres en inglés y francés de iso.org' where id=535;
      UPDATE sip_pais SET nombre='CATAR', nombreiso_espanol='QATAR', observaciones = 'Nombres en inglés y francés de iso.org' where id=634;
      UPDATE sip_pais SET nombre='CHAD', nombreiso_espanol='CHAD', observaciones = 'Nombres en inglés y francés de iso.org' where id=148;
      UPDATE sip_pais SET nombre='CHILE', nombreiso_espanol='CHILE', observaciones = 'Nombres en inglés y francés de iso.org' where id=152;
      UPDATE sip_pais SET nombre='CHINA', nombreiso_espanol='CHINA, REPUBLICA POPULAR', observaciones = 'Nombres en inglés y francés de iso.org' where id=156;
      UPDATE sip_pais SET nombre='CHIPRE', nombreiso_espanol='CHIPRE', observaciones = 'Nombres en inglés y francés de iso.org' where id=196;
      UPDATE sip_pais SET nombre='CIUDAD DEL VATICANO', nombreiso_espanol='SANTA SEDE (CIUDAD ESTADO VATICAVO)', observaciones = 'Nombres en inglés y francés de iso.org' where id=336;
      UPDATE sip_pais SET nombre='COLOMBIA', nombreiso_espanol='COLOMBIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=170;
      UPDATE sip_pais SET nombre='COMORAS', nombreiso_espanol='COMORAS', observaciones = 'Nombres en inglés y francés de iso.org' where id=174;
      UPDATE sip_pais SET nombre='COREA DEL NORTE', nombreiso_espanol='COREA, REPUBLICA DEMOCRATICA POPULAR DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=408;
      UPDATE sip_pais SET nombre='COREA DEL SUR', nombreiso_espanol='COREA, REPUBLICA DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=410;
      UPDATE sip_pais SET nombre='COSTA DE MARFIL', nombreiso_espanol='COSTA DE MARFIL', observaciones = 'Nombres en inglés y francés de iso.org' where id=384;
      UPDATE sip_pais SET nombre='COSTA RICA', nombreiso_espanol='COSTA RICA', observaciones = 'Nombres en inglés y francés de iso.org' where id=188;
      UPDATE sip_pais SET nombre='CROACIA', nombreiso_espanol='CROACIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=191;
      UPDATE sip_pais SET nombre='CUBA', nombreiso_espanol='CUBA', observaciones = 'Nombres en inglés y francés de iso.org' where id=192;
      UPDATE sip_pais SET nombre='CURAZAO', nombreiso_espanol='CURAZAO', observaciones = 'Nombres en inglés y francés de iso.org' where id=531;
      UPDATE sip_pais SET nombre='DINAMARCA', nombreiso_espanol='DINAMARCA', observaciones = 'Nombres en inglés y francés de iso.org' where id=208;
      UPDATE sip_pais SET nombre='DOMINICA', nombreiso_espanol='DOMINICA', observaciones = 'Nombres en inglés y francés de iso.org' where id=212;
      UPDATE sip_pais SET nombre='ECUADOR', nombreiso_espanol='ECUADOR', observaciones = 'Nombres en inglés y francés de iso.org' where id=218;
      UPDATE sip_pais SET nombre='EGIPTO', nombreiso_espanol='EGIPTO', observaciones = 'Nombres en inglés y francés de iso.org' where id=818;
      UPDATE sip_pais SET nombre='EL SALVADOR', nombreiso_espanol='EL SALVADOR', observaciones = 'Nombres en inglés y francés de iso.org' where id=222;
      UPDATE sip_pais SET nombre='EMIRATOS ÁRABES UNIDOS', nombreiso_espanol='EMIRATOS ARABES UNIDOS', observaciones = 'Nombres en inglés y francés de iso.org' where id=784;
      UPDATE sip_pais SET nombre='ERITREA', nombreiso_espanol='ERITREA', observaciones = 'Nombres en inglés y francés de iso.org' where id=232;
      UPDATE sip_pais SET nombre='ESLOVAQUIA', nombreiso_espanol='ESLOVAQUIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=703;
      UPDATE sip_pais SET nombre='ESLOVENIA', nombreiso_espanol='ESLOVENIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=705;
      UPDATE sip_pais SET nombre='ESPAÑA', nombreiso_espanol='ESPAÑA', observaciones = 'Nombres en inglés y francés de iso.org' where id=724;
      UPDATE sip_pais SET nombre='ESTADO DE PALESTINA', nombreiso_espanol='PALESTINA, ESTADO DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=275;
      UPDATE sip_pais SET nombre='ESTADOS UNIDOS', nombreiso_espanol='ESTADOS UNIDOS', observaciones = 'Nombres en inglés y francés de iso.org' where id=840;
      UPDATE sip_pais SET nombre='ESTONIA', nombreiso_espanol='ESTONIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=233;
      UPDATE sip_pais SET nombre='ETIOPÍA', nombreiso_espanol='ETIOPIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=231;
      UPDATE sip_pais SET nombre='FILIPINAS', nombreiso_espanol='FILIPINAS', observaciones = 'Nombres en inglés y francés de iso.org' where id=608;
      UPDATE sip_pais SET nombre='FINLANDIA', nombreiso_espanol='FINLANDIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=246;
      UPDATE sip_pais SET nombre='FIYI', nombreiso_espanol='FIYI', observaciones = 'Nombres en inglés y francés de iso.org' where id=242;
      UPDATE sip_pais SET nombre='FRANCIA', nombreiso_espanol='FRANCIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=250;
      UPDATE sip_pais SET nombre='GABÓN', nombreiso_espanol='GABON', observaciones = 'Nombres en inglés y francés de iso.org' where id=266;
      UPDATE sip_pais SET nombre='GAMBIA', nombreiso_espanol='GAMBIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=270;
      UPDATE sip_pais SET nombre='GEORGIA', nombreiso_espanol='GEORGIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=268;
      UPDATE sip_pais SET nombre='GHANA', nombreiso_espanol='GHANA', observaciones = 'Nombres en inglés y francés de iso.org' where id=288;
      UPDATE sip_pais SET nombre='GIBRALTAR', nombreiso_espanol='GIBRALTAR', observaciones = 'Nombres en inglés y francés de iso.org' where id=292;
      UPDATE sip_pais SET nombre='GRANADA', nombreiso_espanol='GRANADA', observaciones = 'Nombres en inglés y francés de iso.org' where id=308;
      UPDATE sip_pais SET nombre='GRECIA', nombreiso_espanol='GRECIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=300;
      UPDATE sip_pais SET nombre='GROENLANDIA', nombreiso_espanol='GROENLANDIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=304;
      UPDATE sip_pais SET nombre='GUADALUPE', nombreiso_espanol='GUADALUPE', observaciones = 'Nombres en inglés y francés de iso.org' where id=312;
      UPDATE sip_pais SET nombre='GUAM', nombreiso_espanol='GUAM', observaciones = 'Nombres en inglés y francés de iso.org' where id=316;
      UPDATE sip_pais SET nombre='GUATEMALA', nombreiso_espanol='GUATEMALA', observaciones = 'Nombres en inglés y francés de iso.org' where id=320;
      UPDATE sip_pais SET nombre='GUAYANA FRANCESA', nombreiso_espanol='GUAYANA FRANCESA', observaciones = 'Nombres en inglés y francés de iso.org' where id=254;
      UPDATE sip_pais SET nombre='GUERNSEY', nombreiso_espanol='GUERNSEY', observaciones = 'Nombres en inglés y francés de iso.org' where id=831;
      UPDATE sip_pais SET nombre='GUINEA', nombreiso_espanol='GUINEA', observaciones = 'Nombres en inglés y francés de iso.org' where id=324;
      UPDATE sip_pais SET nombre='GUINEA ECUATORIAL', nombreiso_espanol='GUINEA ECUATORIAL', observaciones = 'Nombres en inglés y francés de iso.org' where id=226;
      UPDATE sip_pais SET nombre='GUINEA-BISÁU', nombreiso_espanol='GUINEA-BISAU', observaciones = 'Nombres en inglés y francés de iso.org' where id=624;
      UPDATE sip_pais SET nombre='GUYANA', nombreiso_espanol='GUYANA', observaciones = 'Nombres en inglés y francés de iso.org' where id=328;
      UPDATE sip_pais SET nombre='HAITÍ', nombreiso_espanol='HAITI', observaciones = 'Nombres en inglés y francés de iso.org' where id=332;
      UPDATE sip_pais SET nombre='HONDURAS', nombreiso_espanol='HONDURAS', observaciones = 'Nombres en inglés y francés de iso.org' where id=340;
      UPDATE sip_pais SET nombre='HONG KONG', nombreiso_espanol='HONG KONG', observaciones = 'Nombres en inglés y francés de iso.org' where id=344;
      UPDATE sip_pais SET nombre='HUNGRÍA', nombreiso_espanol='HUNGRIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=348;
      UPDATE sip_pais SET nombre='INDIA', nombreiso_espanol='INDIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=356;
      UPDATE sip_pais SET nombre='INDONESIA', nombreiso_espanol='INDONESIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=360;
      UPDATE sip_pais SET nombre='IRAK', nombreiso_espanol='IRAK', observaciones = 'Nombres en inglés y francés de iso.org' where id=368;
      UPDATE sip_pais SET nombre='IRÁN', nombreiso_espanol='IRAN, REPUBLICA ISLAMICA DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=364;
      UPDATE sip_pais SET nombre='IRLANDA', nombreiso_espanol='IRLANDA', observaciones = 'Nombres en inglés y francés de iso.org' where id=372;
      UPDATE sip_pais SET nombre='ISLA BOUVET', nombreiso_espanol='ISLA BOUVET', observaciones = 'Nombres en inglés y francés de iso.org' where id=74;
      UPDATE sip_pais SET nombre='ISLA DE MAN', nombreiso_espanol='ISLA DE MAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=833;
      UPDATE sip_pais SET nombre='ISLA DE NAVIDAD', nombreiso_espanol='ISLA DE NAVIDAD', observaciones = 'Nombres en inglés y francés de iso.org' where id=162;
      UPDATE sip_pais SET nombre='ISLANDIA', nombreiso_espanol='ISLANDIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=352;
      UPDATE sip_pais SET nombre='ISLAS CAIMÁN', nombreiso_espanol='ISLAS CAIMAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=136;
      UPDATE sip_pais SET nombre='ISLAS COCOS', nombreiso_espanol='ISLAS COCOS (KEELING)', observaciones = 'Nombres en inglés y francés de iso.org' where id=166;
      UPDATE sip_pais SET nombre='ISLAS COOK', nombreiso_espanol='ISLAS COOK', observaciones = 'Nombres en inglés y francés de iso.org' where id=184;
      UPDATE sip_pais SET nombre='ISLAS FEROE', nombreiso_espanol='ISLAS FEROE', observaciones = 'Nombres en inglés y francés de iso.org' where id=234;
      UPDATE sip_pais SET nombre='ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', nombreiso_espanol='ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', observaciones = 'Nombres en inglés y francés de iso.org' where id=239;
      UPDATE sip_pais SET nombre='ISLAS HEARD Y MCDONALD', nombreiso_espanol='ISLAS HEARD Y MCDONALD', observaciones = 'Nombres en inglés y francés de iso.org' where id=334;
      UPDATE sip_pais SET nombre='ISLAS MALVINAS', nombreiso_espanol='ISLAS FALKLAND ( MALVINAS )', observaciones = 'Nombres en inglés y francés de iso.org' where id=238;
      UPDATE sip_pais SET nombre='ISLAS MARIANAS DEL NORTE', nombreiso_espanol='ISLAS MARIANAS DEL NORTE', observaciones = 'Nombres en inglés y francés de iso.org' where id=580;
      UPDATE sip_pais SET nombre='ISLAS MARSHALL', nombreiso_espanol='ISLAS MARSHALL', observaciones = 'Nombres en inglés y francés de iso.org' where id=584;
      UPDATE sip_pais SET nombre='ISLAS PITCAIRN', nombreiso_espanol='PITCAIRN', observaciones = 'Nombres en inglés y francés de iso.org' where id=612;
      UPDATE sip_pais SET nombre='ISLAS SALOMÓN', nombreiso_espanol='ISLAS SALOMON', observaciones = 'Nombres en inglés y francés de iso.org' where id=90;
      UPDATE sip_pais SET nombre='ISLAS TURCAS Y CAICOS', nombreiso_espanol='ISLAS TURCAS Y CAICOS', observaciones = 'Nombres en inglés y francés de iso.org' where id=796;
      UPDATE sip_pais SET nombre='ISLAS ULTRAMARINAS DE ESTADOS UNIDOS', nombreiso_espanol='ISLAS ULTRAMARINAS MENORES DE ESTADOS UNIDOS', observaciones = 'Nombres en inglés y francés de iso.org' where id=581;
      UPDATE sip_pais SET nombre='ISLAS VÍRGENES BRITÁNICAS', nombreiso_espanol='ISLAS VIRGENES BRITANICAS', observaciones = 'Nombres en inglés y francés de iso.org' where id=92;
      UPDATE sip_pais SET nombre='ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', nombreiso_espanol='ISLAS VIRGENES DE LOS ESTADOS UNIDOS', observaciones = 'Nombres en inglés y francés de iso.org' where id=850;
      UPDATE sip_pais SET nombre='ISRAEL', nombreiso_espanol='ISRAEL', observaciones = 'Nombres en inglés y francés de iso.org' where id=376;
      UPDATE sip_pais SET nombre='ITALIA', nombreiso_espanol='ITALIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=380;
      UPDATE sip_pais SET nombre='JAMAICA', nombreiso_espanol='JAMAICA', observaciones = 'Nombres en inglés y francés de iso.org' where id=388;
      UPDATE sip_pais SET nombre='JAPÓN', nombreiso_espanol='JAPON', observaciones = 'Nombres en inglés y francés de iso.org' where id=392;
      UPDATE sip_pais SET nombre='JERSEY', nombreiso_espanol='JERSEY', observaciones = 'Nombres en inglés y francés de iso.org' where id=832;
      UPDATE sip_pais SET nombre='JORDANIA', nombreiso_espanol='JORDANIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=400;
      UPDATE sip_pais SET nombre='KAZAJISTÁN', nombreiso_espanol='KAZAJISTAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=398;
      UPDATE sip_pais SET nombre='KENIA', nombreiso_espanol='KENIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=404;
      UPDATE sip_pais SET nombre='KIRGUISTÁN', nombreiso_espanol='KIRGUISTAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=417;
      UPDATE sip_pais SET nombre='KIRIBATI', nombreiso_espanol='KIRIBATI', observaciones = 'Nombres en inglés y francés de iso.org' where id=296;
      UPDATE sip_pais SET nombre='KUWAIT', nombreiso_espanol='KUWAIT', observaciones = 'Nombres en inglés y francés de iso.org' where id=414;
      UPDATE sip_pais SET nombre='LAOS', nombreiso_espanol='REPUBLICA DEMOCRATICA POPULAR LAO', observaciones = 'Nombres en inglés y francés de iso.org' where id=418;
      UPDATE sip_pais SET nombre='LESOTO', nombreiso_espanol='LESOTO', observaciones = 'Nombres en inglés y francés de iso.org' where id=426;
      UPDATE sip_pais SET nombre='LETONIA', nombreiso_espanol='LETONIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=428;
      UPDATE sip_pais SET nombre='LÍBANO', nombreiso_espanol='LIBANO', observaciones = 'Nombres en inglés y francés de iso.org' where id=422;
      UPDATE sip_pais SET nombre='LIBERIA', nombreiso_espanol='LIBERIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=430;
      UPDATE sip_pais SET nombre='LIBIA', nombreiso_espanol='LIBIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=434;
      UPDATE sip_pais SET nombre='LIECHTENSTEIN', nombreiso_espanol='LIECHTENSTEIN', observaciones = 'Nombres en inglés y francés de iso.org' where id=438;
      UPDATE sip_pais SET nombre='LITUANIA', nombreiso_espanol='LITUANIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=440;
      UPDATE sip_pais SET nombre='LUXEMBURGO', nombreiso_espanol='LUXEMBURGO', observaciones = 'Nombres en inglés y francés de iso.org' where id=442;
      UPDATE sip_pais SET nombre='MACAO', nombreiso_espanol='MACAO', observaciones = 'Nombres en inglés y francés de iso.org' where id=446;
      UPDATE sip_pais SET nombre='MADAGASCAR', nombreiso_espanol='MADAGASCAR', observaciones = 'Nombres en inglés y francés de iso.org' where id=450;
      UPDATE sip_pais SET nombre='MALASIA', nombreiso_espanol='MALASIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=458;
      UPDATE sip_pais SET nombre='MALAUI', nombreiso_espanol='MALAUI', observaciones = 'Nombres en inglés y francés de iso.org' where id=454;
      UPDATE sip_pais SET nombre='MALDIVAS', nombreiso_espanol='MALDIVAS', observaciones = 'Nombres en inglés y francés de iso.org' where id=462;
      UPDATE sip_pais SET nombre='MALÍ', nombreiso_espanol='MALI', observaciones = 'Nombres en inglés y francés de iso.org' where id=466;
      UPDATE sip_pais SET nombre='MALTA', nombreiso_espanol='MALTA', observaciones = 'Nombres en inglés y francés de iso.org' where id=470;
      UPDATE sip_pais SET nombre='MARRUECOS', nombreiso_espanol='MARRUECOS', observaciones = 'Nombres en inglés y francés de iso.org' where id=504;
      UPDATE sip_pais SET nombre='MARTINICA', nombreiso_espanol='MARTINICA', observaciones = 'Nombres en inglés y francés de iso.org' where id=474;
      UPDATE sip_pais SET nombre='MAURICIO', nombreiso_espanol='MAURICIO', observaciones = 'Nombres en inglés y francés de iso.org' where id=480;
      UPDATE sip_pais SET nombre='MAURITANIA', nombreiso_espanol='MAURITANIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=478;
      UPDATE sip_pais SET nombre='MAYOTTE', nombreiso_espanol='MAYOTTE', observaciones = 'Nombres en inglés y francés de iso.org' where id=175;
      UPDATE sip_pais SET nombre='MÉXICO', nombreiso_espanol='MEXICO', observaciones = 'Nombres en inglés y francés de iso.org' where id=484;
      UPDATE sip_pais SET nombre='MICRONESIA', nombreiso_espanol='MICRONESIA, ESTADOS FEDERADOS DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=583;
      UPDATE sip_pais SET nombre='MOLDAVIA', nombreiso_espanol='MOLDAVIA, REPUBLICA DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=498;
      UPDATE sip_pais SET nombre='MÓNACO', nombreiso_espanol='MONACO', observaciones = 'Nombres en inglés y francés de iso.org' where id=492;
      UPDATE sip_pais SET nombre='MONGOLIA', nombreiso_espanol='MONGOLIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=496;
      UPDATE sip_pais SET nombre='MONTENEGRO', nombreiso_espanol='MONTENEGRO', observaciones = 'Nombres en inglés y francés de iso.org' where id=499;
      UPDATE sip_pais SET nombre='MONTSERRAT', nombreiso_espanol='MONTSERRAT', observaciones = 'Nombres en inglés y francés de iso.org' where id=500;
      UPDATE sip_pais SET nombre='MOZAMBIQUE', nombreiso_espanol='MOZAMBIQUE', observaciones = 'Nombres en inglés y francés de iso.org' where id=508;
      UPDATE sip_pais SET nombre='NAMIBIA', nombreiso_espanol='NABIMIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=516;
      UPDATE sip_pais SET nombre='NAURU', nombreiso_espanol='NAURU', observaciones = 'Nombres en inglés y francés de iso.org' where id=520;
      UPDATE sip_pais SET nombre='NEPAL', nombreiso_espanol='NEPAL', observaciones = 'Nombres en inglés y francés de iso.org' where id=524;
      UPDATE sip_pais SET nombre='NICARAGUA', nombreiso_espanol='NICARAGUA', observaciones = 'Nombres en inglés y francés de iso.org' where id=558;
      UPDATE sip_pais SET nombre='NÍGER', nombreiso_espanol='NIGER', observaciones = 'Nombres en inglés y francés de iso.org' where id=562;
      UPDATE sip_pais SET nombre='NIGERIA', nombreiso_espanol='NIGERIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=566;
      UPDATE sip_pais SET nombre='NIUE', nombreiso_espanol='NIUE', observaciones = 'Nombres en inglés y francés de iso.org' where id=570;
      UPDATE sip_pais SET nombre='NORFOLK', nombreiso_espanol='ISLA NORFOLK', observaciones = 'Nombres en inglés y francés de iso.org' where id=574;
      UPDATE sip_pais SET nombre='NORUEGA', nombreiso_espanol='NORUEGA', observaciones = 'Nombres en inglés y francés de iso.org' where id=578;
      UPDATE sip_pais SET nombre='NUEVA CALEDONIA', nombreiso_espanol='NUEVA CALEDONIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=540;
      UPDATE sip_pais SET nombre='NUEVA ZELANDA', nombreiso_espanol='NUEVA ZELANDA', observaciones = 'Nombres en inglés y francés de iso.org' where id=554;
      UPDATE sip_pais SET nombre='OMÁN', nombreiso_espanol='OMAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=512;
      UPDATE sip_pais SET nombre='PAÍSES BAJOS', nombreiso_espanol='PAISES BAJOS', observaciones = 'Nombres en inglés y francés de iso.org' where id=528;
      UPDATE sip_pais SET nombre='PAKISTÁN', nombreiso_espanol='PAKISTAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=586;
      UPDATE sip_pais SET nombre='PALAOS', nombreiso_espanol='PALAOS', observaciones = 'Nombres en inglés y francés de iso.org' where id=585;
      UPDATE sip_pais SET nombre='PANAMÁ', nombreiso_espanol='PANAMA', observaciones = 'Nombres en inglés y francés de iso.org' where id=591;
      UPDATE sip_pais SET nombre='PAPÚA NUEVA GUINEA', nombreiso_espanol='PAPUA NUEVA GUINEA', observaciones = 'Nombres en inglés y francés de iso.org' where id=598;
      UPDATE sip_pais SET nombre='PARAGUAY', nombreiso_espanol='PARAGUAY', observaciones = 'Nombres en inglés y francés de iso.org' where id=600;
      UPDATE sip_pais SET nombre='PERÚ', nombreiso_espanol='PERU', observaciones = 'Nombres en inglés y francés de iso.org' where id=604;
      UPDATE sip_pais SET nombre='POLINESIA FRANCESA', nombreiso_espanol='POLINESIA FRANCESA', observaciones = 'Nombres en inglés y francés de iso.org' where id=258;
      UPDATE sip_pais SET nombre='POLONIA', nombreiso_espanol='POLONIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=616;
      UPDATE sip_pais SET nombre='PORTUGAL', nombreiso_espanol='PORTUGAL', observaciones = 'Nombres en inglés y francés de iso.org' where id=620;
      UPDATE sip_pais SET nombre='PUERTO RICO', nombreiso_espanol='PUERTO RICO', observaciones = 'Nombres en inglés y francés de iso.org' where id=630;
      UPDATE sip_pais SET nombre='REINO UNIDO', nombreiso_espanol='REINO UNIDO', observaciones = 'Nombres en inglés y francés de iso.org' where id=826;
      UPDATE sip_pais SET nombre='REPÚBLICA CENTROAFRICANA', nombreiso_espanol='REPUBLICA CENTROAFRICANA', observaciones = 'Nombres en inglés y francés de iso.org' where id=140;
      UPDATE sip_pais SET nombre='REPÚBLICA CHECA', nombreiso_espanol='REPUBLICA CHECA', observaciones = 'Nombres en inglés y francés de iso.org' where id=203;
      UPDATE sip_pais SET nombre='REPÚBLICA DE MACEDONIA', nombreiso_espanol='MACEDONIA, LA ANTIGUA REPUBLICA YUGOSLAVA DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=807;
      UPDATE sip_pais SET nombre='REPÚBLICA DEL CONGO', nombreiso_espanol='CONGO', observaciones = 'Nombres en inglés y francés de iso.org' where id=178;
      UPDATE sip_pais SET nombre='REPÚBLICA DEMOCRÁTICA DEL CONGO', nombreiso_espanol='CONGO, LA REPUBLICA DEMOCRATICA DEL', observaciones = 'Nombres en inglés y francés de iso.org' where id=180;
      UPDATE sip_pais SET nombre='REPÚBLICA DOMINICANA', nombreiso_espanol='REPUBLICA DOMINICANA', observaciones = 'Nombres en inglés y francés de iso.org' where id=214;
      UPDATE sip_pais SET nombre='REUNIÓN', nombreiso_espanol='REUNION', observaciones = 'Nombres en inglés y francés de iso.org' where id=638;
      UPDATE sip_pais SET nombre='RUANDA', nombreiso_espanol='RUANDA', observaciones = 'Nombres en inglés y francés de iso.org' where id=646;
      UPDATE sip_pais SET nombre='RUMANIA', nombreiso_espanol='RUMANIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=642;
      UPDATE sip_pais SET nombre='RUSIA', nombreiso_espanol='FEDERACION RUSA', observaciones = 'Nombres en inglés y francés de iso.org' where id=643;
      UPDATE sip_pais SET nombre='SAHARA OCCIDENTAL', nombreiso_espanol='SAHARA OCCIDENTAL', observaciones = 'Nombres en inglés y francés de iso.org' where id=732;
      UPDATE sip_pais SET nombre='SAMOA', nombreiso_espanol='SAMOA', observaciones = 'Nombres en inglés y francés de iso.org' where id=882;
      UPDATE sip_pais SET nombre='SAMOA AMERICANA', nombreiso_espanol='SAMOA AMERICANA', observaciones = 'Nombres en inglés y francés de iso.org' where id=16;
      UPDATE sip_pais SET nombre='SAN BARTOLOMÉ', nombreiso_espanol='SAN BARTOLOME', observaciones = 'Nombres en inglés y francés de iso.org' where id=652;
      UPDATE sip_pais SET nombre='SAN CRISTÓBAL Y NIEVES', nombreiso_espanol='SAN CRISTOBAL Y NIEVES', observaciones = 'Nombres en inglés y francés de iso.org' where id=659;
      UPDATE sip_pais SET nombre='SAN MARINO', nombreiso_espanol='SAN MARINO', observaciones = 'Nombres en inglés y francés de iso.org' where id=674;
      UPDATE sip_pais SET nombre='SAN MARTÍN', nombreiso_espanol='SAN MARTIN (PARTE FRANCESA)', observaciones = 'Nombres en inglés y francés de iso.org' where id=663;
      UPDATE sip_pais SET nombre='SAN PEDRO Y MIQUELÓN', nombreiso_espanol='SAN PEDRO Y MIQUELON', observaciones = 'Nombres en inglés y francés de iso.org' where id=666;
      UPDATE sip_pais SET nombre='SAN VICENTE Y LAS GRANADINAS', nombreiso_espanol='SAN VICENTE Y LAS GRANADINAS', observaciones = 'Nombres en inglés y francés de iso.org' where id=670;
      UPDATE sip_pais SET nombre='SANTA HELENA, A. Y T.', nombreiso_espanol='SANTA HELENA, ASCENSION Y TRISTAN DE ACUÑA', observaciones = 'Nombres en inglés y francés de iso.org' where id=654;
      UPDATE sip_pais SET nombre='SANTA LUCÍA', nombreiso_espanol='SANTA LUCIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=662;
      UPDATE sip_pais SET nombre='SANTO TOMÉ Y PRÍNCIPE', nombreiso_espanol='SANTO TOME Y PRINCIPE', observaciones = 'Nombres en inglés y francés de iso.org' where id=678;
      UPDATE sip_pais SET nombre='SENEGAL', nombreiso_espanol='SENEGAL', observaciones = 'Nombres en inglés y francés de iso.org' where id=686;
      UPDATE sip_pais SET nombre='SERBIA', nombreiso_espanol='SERBIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=688;
      UPDATE sip_pais SET nombre='SEYCHELLES', nombreiso_espanol='SEYCHELLES', observaciones = 'Nombres en inglés y francés de iso.org' where id=690;
      UPDATE sip_pais SET nombre='SIERRA LEONA', nombreiso_espanol='SIERRA LEONA', observaciones = 'Nombres en inglés y francés de iso.org' where id=694;
      UPDATE sip_pais SET nombre='SINGAPUR', nombreiso_espanol='SINGAPUR', observaciones = 'Nombres en inglés y francés de iso.org' where id=702;
      UPDATE sip_pais SET nombre='SINT MAARTEN', nombreiso_espanol='SINT MAARTEN (PARTE NEERLANDESA)', observaciones = 'Nombres en inglés y francés de iso.org' where id=534;
      UPDATE sip_pais SET nombre='SIRIA', nombreiso_espanol='REPUBLICA ARABE DE SIRIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=760;
      UPDATE sip_pais SET nombre='SOMALIA', nombreiso_espanol='SOMALIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=706;
      UPDATE sip_pais SET nombre='SRI LANKA', nombreiso_espanol='SRI LANKA', observaciones = 'Nombres en inglés y francés de iso.org' where id=144;
      UPDATE sip_pais SET nombre='SUAZILANDIA', nombreiso_espanol='SUAZILANDIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=748;
      UPDATE sip_pais SET nombre='SUDÁFRICA', nombreiso_espanol='SUDAFRICA', observaciones = 'Nombres en inglés y francés de iso.org' where id=710;
      UPDATE sip_pais SET nombre='SUDÁN', nombreiso_espanol='SUDAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=729;
      UPDATE sip_pais SET nombre='SUDÁN DEL SUR', nombreiso_espanol='SUDAN DEL SUR', observaciones = 'Nombres en inglés y francés de iso.org' where id=728;
      UPDATE sip_pais SET nombre='SUECIA', nombreiso_espanol='SUECIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=752;
      UPDATE sip_pais SET nombre='SUIZA', nombreiso_espanol='SUIZA', observaciones = 'Nombres en inglés y francés de iso.org' where id=756;
      UPDATE sip_pais SET nombre='SURINAM', nombreiso_espanol='SURINAM', observaciones = 'Nombres en inglés y francés de iso.org' where id=740;
      UPDATE sip_pais SET nombre='SVALBARD Y JAN MAYEN', nombreiso_espanol='SVALBARD Y JAN MAYEN', observaciones = 'Nombres en inglés y francés de iso.org' where id=744;
      UPDATE sip_pais SET nombre='TAILANDIA', nombreiso_espanol='TAILANDIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=764;
      UPDATE sip_pais SET nombre='TAIWÁN', nombreiso_espanol='TAIWAN, PROVINCIA DE CHINA', observaciones = 'Nombres en inglés y francés de iso.org' where id=158;
      UPDATE sip_pais SET nombre='TANZANIA', nombreiso_espanol='TANZANIA, REPUBLICA UNIDA DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=834;
      UPDATE sip_pais SET nombre='TAYIKISTÁN', nombreiso_espanol='TAYIKISTAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=762;
      UPDATE sip_pais SET nombre='TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', nombreiso_espanol='TERRITORIO BRITANICO DEL OCEANO INDICO', observaciones = 'Nombres en inglés y francés de iso.org' where id=86;
      UPDATE sip_pais SET nombre='TERRITORIOS AUSTRALES FRANCESES', nombreiso_espanol='TERRITORIOS AUSTRALES FRANCESES', observaciones = 'Nombres en inglés y francés de iso.org' where id=260;
      UPDATE sip_pais SET nombre='TIMOR ORIENTAL', nombreiso_espanol='TIMOR-LESTE', observaciones = 'Nombres en inglés y francés de iso.org' where id=626;
      UPDATE sip_pais SET nombre='TOGO', nombreiso_espanol='TOGO', observaciones = 'Nombres en inglés y francés de iso.org' where id=768;
      UPDATE sip_pais SET nombre='TOKELAU', nombreiso_espanol='TOKELAU', observaciones = 'Nombres en inglés y francés de iso.org' where id=772;
      UPDATE sip_pais SET nombre='TONGA', nombreiso_espanol='TONGA', observaciones = 'Nombres en inglés y francés de iso.org' where id=776;
      UPDATE sip_pais SET nombre='TRINIDAD Y TOBAGO', nombreiso_espanol='TRINIDAD Y TOBAGO', observaciones = 'Nombres en inglés y francés de iso.org' where id=780;
      UPDATE sip_pais SET nombre='TÚNEZ', nombreiso_espanol='TUNEZ', observaciones = 'Nombres en inglés y francés de iso.org' where id=788;
      UPDATE sip_pais SET nombre='TURKMENISTÁN', nombreiso_espanol='TURKMENISTAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=795;
      UPDATE sip_pais SET nombre='TURQUÍA', nombreiso_espanol='TURQUIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=792;
      UPDATE sip_pais SET nombre='TUVALU', nombreiso_espanol='TUVALU', observaciones = 'Nombres en inglés y francés de iso.org' where id=798;
      UPDATE sip_pais SET nombre='UCRANIA', nombreiso_espanol='UCRANIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=804;
      UPDATE sip_pais SET nombre='UGANDA', nombreiso_espanol='UGANDA', observaciones = 'Nombres en inglés y francés de iso.org' where id=800;
      UPDATE sip_pais SET nombre='URUGUAY', nombreiso_espanol='URUGUAY', observaciones = 'Nombres en inglés y francés de iso.org' where id=858;
      UPDATE sip_pais SET nombre='UZBEKISTÁN', nombreiso_espanol='UZBEKISTAN', observaciones = 'Nombres en inglés y francés de iso.org' where id=860;
      UPDATE sip_pais SET nombre='VANUATU', nombreiso_espanol='VANUATU', observaciones = 'Nombres en inglés y francés de iso.org' where id=548;
      UPDATE sip_pais SET nombre='VENEZUELA', nombreiso_espanol='VENEZUELA, REPUBLICA BOLIVARIANA DE', observaciones = 'Nombres en inglés y francés de iso.org' where id=862;
      UPDATE sip_pais SET nombre='VIETNAM', nombreiso_espanol='VIET NAM', observaciones = 'Nombres en inglés y francés de iso.org' where id=704;
      UPDATE sip_pais SET nombre='Wallis y Futuna', nombreiso_espanol='Wallis y Futuna', observaciones = 'Nombres en inglés y francés de iso.org' where id=876;
      UPDATE sip_pais SET nombre='YEMEN', nombreiso_espanol='YEMEN', observaciones = 'Nombres en inglés y francés de iso.org' where id=887;
      UPDATE sip_pais SET nombre='YIBUTI', nombreiso_espanol='YIBUTI', observaciones = 'Nombres en inglés y francés de iso.org' where id=262;
      UPDATE sip_pais SET nombre='ZAMBIA', nombreiso_espanol='ZAMBIA', observaciones = 'Nombres en inglés y francés de iso.org' where id=894;
      UPDATE sip_pais SET nombre='ZIMBABUE', nombreiso_espanol='ZIMBABUE', observaciones = 'Nombres en inglés y francés de iso.org' where id=716;
    SQL
  end
end
